### ISSUE TITLE
Activity is not displayed in the Place card - version 1.2.2

### ISSUE THREAD

**Issue by MaliheTabasi** [e-mission/e-mission-docs#882] opened 2023-04-09 04:01 UTC
@shankari  Please watch the below screen recording. I tried to add activity to the last Place card and it is not displayed there.
Moreover, the prefilled end time is expected to be 11:59PM, but it is 10:25PM.

https://user-images.githubusercontent.com/49550315/230753537-f854eafb-a33d-4821-83f3-a3e8f3fde508.mp4

**Comment by MaliheTabasi** [comment] 2023-04-13 01:06
@shankari  This is a fundamental issue. Can you pls prioritise this one?

**Comment by shankari** [comment] 2023-04-13 23:43
@MaliheTabasi please retry with 1.2.3 - note that the more complicated P0 issue https://github.com/e-mission/e-mission-docs/issues/880 was that all the place activities were being associated with the first place.

**Comment by MaliheTabasi** [comment] 2023-04-14 00:18
@shankari  Thank you for letting me know. I will try version 1.2.3.

**Comment by MaliheTabasi** [comment] 2023-04-17 06:20
@shankari  I still faced the same issue with version 1.2.3 as can be seen in the attached screen recording.


https://user-images.githubusercontent.com/49550315/232399250-e4450c07-38e6-4230-bf6f-ed628d5546cd.mp4

**Comment by shankari** [comment] 2023-04-18 21:20
@MaliheTabasi I cannot reproduce this on 1.2.3 (see attached video)

Can you:
- confirm that the version is in fact 1.2.3? You can check the version in TestFlight and also in the app (Profile -> Developer Zone -> Scroll to the bottom)
- retry one more time? Check if the first place entry ends at midnight - that is the underlying issue

If you are still able to reproduce, and I am not, this is likely to be related to your data.
Please send me your token via email and I will log in as you and see if I can reproduce.

**Comment by MaliheTabasi** [comment] 2023-04-19 12:28
> @MaliheTabasi I cannot reproduce this on 1.2.3 (see attached video)
> 
>  time_use_entries_added.mov 
> Can you:
> 
> * confirm that the version is in fact 1.2.3? You can check the version in TestFlight and also in the app (Profile -> Developer Zone -> Scroll to the bottom)
> * retry one more time? Check if the first place entry ends at midnight - that is the underlying issue
> 
> If you are still able to reproduce, and I am not, this is likely to be related to your data. Please send me your token via email and I will log in as you and see if I can reproduce.

@shankari  Yes, The version is 1.2.3. I retried. I realised that it works for places and trips before a specific place with end time 11:59pm, but it does not work properly for places after that. The activities I tried to add to places after that specific place were incorrectly displayed in that specific place. I will send you my token so that you can reproduce this error.

**Comment by MaliheTabasi** [comment] 2023-04-19 12:34
> @shankari Please watch the below screen recording. I tried to add activity to the last Place card and it is not displayed there. Moreover, the prefilled end time is expected to be 11:59PM, but it is 10:25PM.
> 
>  video6167770506767370496.mp4

@shankari  I still see the issue of wrong place end time in the app. Please see the screenshot below. Place end time is expected to be 11:59pm but it is 1:51pm.

![photo1681888397](https://user-images.githubusercontent.com/49550315/233075807-71c9f3e0-a395-47f1-ac04-675ad7842200.jpeg)

**Comment by shankari** [comment] 2023-04-19 15:45
@MaliheTabasi I'm pretty sure this is an overnight place. The issue of how to represent and deal with overnight places is still open
https://github.com/e-mission/e-mission-docs/issues/871#issuecomment-1489740498
https://github.com/e-mission/e-mission-docs/issues/871#issuecomment-1489750959

We had de-prioritized that design based on this comment

https://github.com/e-mission/e-mission-docs/issues/871#issuecomment-1495465078
> Taha and I had a meeting and decided that activities that starts form one day and ends in another day are not essential for our study. So, we can stop worrying about that and instead focus on fixing the errors with the current basic time-use feature.

However, I think we do need to address it before going live, since sleeping overnight is a very common use case.
Opening a new issue for it.
https://github.com/e-mission/e-mission-docs/issues/891

**Comment by shankari** [comment] 2023-04-19 20:23
@MaliheTabasi can you re-retry? I just tried and it works fine. The 11:59 place is gone (replaced by untracked time) and the activities have been matched to their correct places.

| 11:59 place is gone | Activities have been moved to the correct following places |
|--------|--------|
| ![simulator_screenshot_EC3B715B-7F84-447E-B866-7EC29B85FE84](https://user-images.githubusercontent.com/2423263/233189813-e1832fad-b173-4beb-9485-6701191113b8.png) | ![simulator_screenshot_EAE27B9B-B846-4E78-AC3F-66F1C4E52CB1](https://user-images.githubusercontent.com/2423263/233189984-648d4043-a116-4fda-b82b-9cb2e70a71e6.png) |

The issue was that I had not reset the pipeline for your token. Note that the fix for #880 was primarily on the server side; we were creating the confirmed timeline incorrectly. So to fix, I needed to reset the pipeline and reconstruct the confirmed timeline. Fortunately OpenPATH is set up to do this without losing user data.

Rather than overloading the server, I went through and reset pipelines in order of last trip date. Your last trip was from 11th Apr, so it was towards the end of the queue. And it looks like I marked it as reset without actually resetting it. Oops!

I reset again today morning, the timeline has been regenerated and everything should work now.
As an aside, this also fixes #890 as you can see from the screenshots

**Comment by shankari** [comment] 2023-04-26 01:25
Closing this since resetting the pipeline has fixed the issue

**Closed by shankari** 2023-04-26 01:25 UTC
