### ISSUE TITLE
trip confirm for mode and purpose dated 1/1/70

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#413] opened 2019-06-11 12:24 UTC
Sometimes (I have still understand under which circumstances this occurs), at the end of a trip, the mode and purpose confirmation UI is dated on January 1st, 1970. We will investigate further but I thought useful to mention the issue here.

**Comment by shankari** [comment] 2019-06-12 16:36
is this the trip-end prompt or the list view?

**Comment by PatGendre** [comment] 2019-06-12 16:53
The trip end prompt

**Comment by PatGendre** [comment] 2019-07-05 11:00
@shankari  @DO3B 
Hi, Loïc published a new app version which includes [your commit](https://github.com/e-mission/e-mission-phone/commit/6b9da247e989f29b38a0afb8f3c4351a5630d13f) but I've still seen this morning a trip end notification screen dated in 1/1/70  (though afterwards in the diary the trip is correctly displayed for today's date).
I'll tell you if this happens again.

**Comment by shankari** [comment] 2019-07-05 14:17
@PatGendre I checked in a **potential** fix but wasn't sure that was even addressing the underlying cause since we haven't been able to reproduce it. I also did add additional logging, so if you send me the logs, or look at them yourself (https://github.com/e-mission/e-mission-docs/blob/master/docs/manage/troubleshooting_app_faq.md#reading-the-log-on-your-computer) we can try to figure out more about the root cause.

**Comment by PatGendre** [comment] 2019-07-05 14:56
@shankari Ok I looked at the logs but I don't find any 1970 string, so I looked at the post-trips-prompts of today, there are three, but I cannot see any confirmation of 1/1/1907 having been displayed.
@DO3B Loïc told me that this could be caused by the momentjs lib ?

EX. 1
`2777,1562315824.101,2019-07-05 10:37:04.101000+00:09,js : registerUserResponse received!
2778,1562315824.113,2019-07-05 10:37:04.113000+00:09,js : registertripEnd received!
2779,1562315824.144,2019-07-05 10:37:04.144000+00:09,"js : Returning notification config {""id"":737678,""title"":""post-trip-prompt.notification-title"",""text"":""post-trip-prompt.platform-specific-message-android"",""icon"":""file://img/icon.png"",""smallIcon"":""res://ic_mood_question.png"",""sound"":null,""actions"":[{""identifier"":""MUTE"",""title"":""post-trip-prompt.notification-option-mute"",""icon"":""res://ic_moreoptions"",""activationMode"":""background"",""destructive"":false,""authenticationRequired"":false},{""identifier"":""SNOOZE"",""title"":""post-trip-prompt.notification-option-snooze"",""icon"":""res://ic_moreoptions"",""activationMode"":""background"",""destructive"":false,""authenticationRequired"":false},{""identifier"":""CHOOSE"",""title"":""post-trip-prompt.notification-option-choose"",""icon"":""res://ic_signin"",""activationMode"":""foreground"",""destructive"":false,""authenticationRequired"":false}],""category"":""TRIP_CONFIRM"",""autoClear"":true}"
2780,1562315824.151,2019-07-05 10:37:04.151000+00:09,"TransitionNotifier : configuration changed, changing object at index 0"
2781,1562315824.16,2019-07-05 10:37:04.160000+00:09,BuiltinUserCache : Added value for key trip_ended at time 1.562315824155E9
2782,1562315824.1660001,2019-07-05 10:37:04.166000+00:09,js : registerUserResponse received!
278`

EX. 2
`5322,1562319986.889,2019-07-05 11:46:26.889000+00:09,js : pushnotify startup done
5323,1562319986.895,2019-07-05 11:46:26.895000+00:09,js : registerUserResponse received!
5324,1562319986.905,2019-07-05 11:46:26.905000+00:09,js : registertripEnd received!
5325,1562319986.9420002,2019-07-05 11:46:26.942000+00:09,"js : Returning notification config {""id"":737678,""title"":""post-trip-prompt.notification-title"",""text"":""post-trip-prompt.platform-specific-message-android"",""icon"":""file://img/icon.png"",""smallIcon"":""res://ic_mood_question.png"",""sound"":null,""actions"":[{""identifier"":""MUTE"",""title"":""post-trip-prompt.notification-option-mute"",""icon"":""res://ic_moreoptions"",""activationMode"":""background"",""destructive"":false,""authenticationRequired"":false},{""identifier"":""SNOOZE"",""title"":""post-trip-prompt.notification-option-snooze"",""icon"":""res://ic_moreoptions"",""activationMode"":""background"",""destructive"":false,""authenticationRequired"":false},{""identifier"":""CHOOSE"",""title"":""post-trip-prompt.notification-option-choose"",""icon"":""res://ic_signin"",""activationMode"":""foreground"",""destructive"":false,""authenticationRequired"":false}],""category"":""TRIP_CONFIRM"",""autoClear"":true}"
5326,1562319986.949,2019-07-05 11:46:26.949000+00:09,"TransitionNotifier : configuration changed, changing object at index 0"
5327,1562319986.958,2019-07-05 11:46:26.958000+00:09,BuiltinUserCache : Added value for key trip_ended at time 1.562319986954E9
5328,1562319986.9629998,2019-07-05 11:46:26.963000+00:09,js : registerUserResponse received!
5329,1562319986.976,2019-07-05 11:46:26.976000+00:09,js : uc_stored_val = null ls_stored_val = null
5330,1562319986.981,2019-07-05 11:46:26.981000+00:09,"js : local and native values match, already synced"
5`

EX.3
`7182,1562334944.043,2019-07-05 15:55:44.043000+00:09,js : registertripEnd received!
7183,1562334944.0839999,2019-07-05 15:55:44.084000+00:09,"js : Returning notification config {""id"":737678,""title"":""post-trip-prompt.notification-title"",""text"":""post-trip-prompt.platform-specific-message-android"",""icon"":""file://img/icon.png"",""smallIcon"":""res://ic_mood_question.png"",""sound"":null,""actions"":[{""identifier"":""MUTE"",""title"":""post-trip-prompt.notification-option-mute"",""icon"":""res://ic_moreoptions"",""activationMode"":""background"",""destructive"":false,""authenticationRequired"":false},{""identifier"":""SNOOZE"",""title"":""post-trip-prompt.notification-option-snooze"",""icon"":""res://ic_moreoptions"",""activationMode"":""background"",""destructive"":false,""authenticationRequired"":false},{""identifier"":""CHOOSE"",""title"":""post-trip-prompt.notification-option-choose"",""icon"":""res://ic_signin"",""activationMode"":""foreground"",""destructive"":false,""authenticationRequired"":false}],""category"":""TRIP_CONFIRM"",""autoClear"":true}"
7184,1562334944.0939999,2019-07-05 15:55:44.094000+00:09,"TransitionNotifier : configuration changed, changing object at index 0"
7185,1562334944.107,2019-07-05 15:55:44.107000+00:09,BuiltinUserCache : Added value for key trip_ended at time 1.5623349441E9
`

In the likely case where I didn't look at the right place, I  attach the logs.
[loggerDB.withdate.log.zip](https://github.com/e-mission/e-mission-docs/files/3363191/loggerDB.withdate.log.zip)

**Comment by shankari** [comment] 2019-07-05 15:35
Yeah those logs are for when we are registering the config for the notifications. We want to look for the logs from 
https://github.com/e-mission/e-mission-phone/pull/592/commits/6b9da247e989f29b38a0afb8f3c4351a5630d13f

which are

```
C02KT61MFFT0:tmp shankari$ egrep "About to display completed trip from notification|entered post-trip map screen" loggerDB.withdate.log
5340,1562319987.079,2019-07-05 11:46:27.079000+00:09,"js : About to display completed trip from notification {""end_ts"":1562318503.874,""end_lat"":43.5220512,""end_lng"":5.4208097,""start_ts"":1562316393,""start_lat"":43.5142,""start_lng"":5.4624383}"
5367,1562319988.8879998,2019-07-05 11:46:28.888000+00:09,"js : entered post-trip map screen, resetting start = null end = null"
5410,1562320003.7979999,2019-07-05 11:46:43.798000+00:09,"js : entered post-trip map screen, prompting for values"
5705,1562320321.188,2019-07-05 11:52:01.188000+00:09,"js : About to display completed trip from notification {""end_ts"":1562320182,""end_lat"":43.5239967,""end_lng"":5.4212,""start_ts"":1562319756.274,""start_lat"":43.5235641,""start_lng"":5.4208282}"
6921,1562321854.9629998,2019-07-05 12:17:34.963000+00:09,"js : About to display completed trip from notification {""end_ts"":1562321721,""end_lat"":43.5180083,""end_lng"":5.4705683,""start_ts"":1562320182,""start_lat"":43.5239967,""start_lng"":5.4212}"
6986,1562324258.508,2019-07-05 12:57:38.508000+00:09,"js : About to display completed trip from notification {""end_ts"":1562321721,""end_lat"":43.5180083,""end_lng"":5.4705683,""start_ts"":1562320182,""start_lat"":43.5239967,""start_lng"":5.4212}"
6997,1562324260.7510002,2019-07-05 12:57:40.751000+00:09,"js : entered post-trip map screen, resetting start = 1562320182 end = 1562321721"
6998,1562324260.7570002,2019-07-05 12:57:40.757000+00:09,"js : entered post-trip map screen, prompting for values"
7016,1562324270.0210001,2019-07-05 12:57:50.021000+00:09,"js : entered post-trip map screen, prompting for values"
```

Couple of things to note:
- `entered post-trip map screen, prompting for values` is actually logged when we leave the screen https://github.com/e-mission/e-mission-phone/blob/732b9c8028ef401082d828f821451886d218bd54/www/js/tripconfirm/post-trip-map-display.js#L50 (need to fix the log message)
- the notifications themselves always have correct values, so the related confirm objects are known to be correct (as you observed later)
```
C02KT61MFFT0:tmp shankari$ egrep "About to display completed trip from notification" loggerDB.withdate.log
5340,1562319987.079,2019-07-05 11:46:27.079000+00:09,"js : About to display completed trip from notification {""end_ts"":1562318503.874,""end_lat"":43.5220512,""end_lng"":5.4208097,""start_ts"":1562316393,""start_lat"":43.5142,""start_lng"":5.4624383}"
5705,1562320321.188,2019-07-05 11:52:01.188000+00:09,"js : About to display completed trip from notification {""end_ts"":1562320182,""end_lat"":43.5239967,""end_lng"":5.4212,""start_ts"":1562319756.274,""start_lat"":43.5235641,""start_lng"":5.4208282}"
6921,1562321854.9629998,2019-07-05 12:17:34.963000+00:09,"js : About to display completed trip from notification {""end_ts"":1562321721,""end_lat"":43.5180083,""end_lng"":5.4705683,""start_ts"":1562320182,""start_lat"":43.5239967,""start_lng"":5.4212}"
6986,1562324258.508,2019-07-05 12:57:38.508000+00:09,"js : About to display completed trip from notification {""end_ts"":1562321721,""end_lat"":43.5180083,""end_lng"":5.4705683,""start_ts"":1562320182,""start_lat"":43.5239967,""start_lng"":5.4212}"
```
- However, we do see that the start and end timestamps are set to null on the first instance

```
5367,1562319988.8879998,2019-07-05 11:46:28.888000+00:09,"js : entered post-trip map screen, resetting start = null end = null"
```

- But right after that, we should have set them https://github.com/e-mission/e-mission-phone/blob/732b9c8028ef401082d828f821451886d218bd54/www/js/tripconfirm/post-trip-map-display.js#L40

I wonder if this is a race between the display and the notification. `$ionicView.enter` is called when we enter the view, but not necessarily **before** entering the view. 
https://www.gajotres.net/understanding-ionic-view-lifecycle/

So one possibility is that the view reads the null value and initializes the HTML element. And once the values are reset, there is no trigger to update the UI.

**Comment by PatGendre** [comment] 2019-07-05 15:44
thanks for having made the diagnostic, I should have checked the code/commit before looking in the logs.

**Comment by shankari** [comment] 2019-07-05 15:46
Some additional evidence that this may be the case:
the display of the timestamps in the tripconfirm map page is using `getFormattedDate`
https://github.com/e-mission/e-mission-phone/blob/master/www/templates/tripconfirm/map.html#L8
which (through indirection from https://github.com/e-mission/e-mission-phone/blob/master/www/js/tripconfirm/post-trip-map-display.js#L168) is implemented in
https://github.com/e-mission/e-mission-phone/blob/master/www/js/diary/services.js#L28

When I try running that code with `null`, I get 

```
moment(null * 1000).format("DD MMMM YYYY")
"31 December 1969"
```

This is close to the observed behavior, but not an exact match. So we don't still know whether this is the correct diagnosis. Let's make the fix anyway and add some additional logging.

**Comment by shankari** [comment] 2019-07-05 15:55
And poking at this some more, the close but not exact behavior is due to timezones. If I run the same code in a European timezone, I do indeed get 1/1/1970

```
moment(null * 1000).tz("Europe/Brussels").format("DD MMMM YYYY")
"01 January 1970"
```

So I am pretty sure that this is the root cause.

@DO3B I will attach a patch here, can you apply it and test it out? Once I know that it works, I can merge to master. I am reluctant to commit untested code, and I don't really have a reproducible way of testing it locally.

**Comment by shankari** [comment] 2019-07-05 16:10
Actually, wait, I don't understand this. I am logging the `$stateParams` and they are null.

```
5367,1562319988.8879998,2019-07-05 11:46:28.888000+00:09,"js : entered post-trip map screen, resetting start = null end = null"
5368,1562319989.1139998,2019-07-05 11:46:29.114000+00:09,js : About to dedup localResult = 0remoteResult = 0
5369,1562319989.1239998,2019-07-05 11:46:29.124000+00:09,js : Deduped list = 0
5370,1562319989.1320002,2019-07-05 11:46:29.132000+00:09,js : Read data of length 0
5371,1562319989.312,2019-07-05 11:46:29.312000+00:09,CommunicationHelper : Got response org.apache.http.message.BasicHttpResponse@5c1a3c with status HTTP/1.1 200 OK
5372,1562319989.322,2019-07-05 11:46:29.322000+00:09,"CommunicationHelper : Result Summary JSON = {""update"": true}
 length 17"
5373,1562320000.2670002,2019-07-05 11:46:40.267000+00:09,"js : in storeMode, after setting mode_val = bike, draftMode = {""start_ts"":null,""end_ts"":null,""label"":""bike""}"
5395,1562320002.52,2019-07-05 11:46:42.520000+00:09,"js : in storePurpose, after setting purpose_val = work, draftPurpose = {""start_ts"":null,""end_ts"":null,""label"":""work""}"
```

Not sure why the `$stateParams` should be null. Sorry for the repeated updates, but I thought this was a simple fix and it is not.

**Comment by shankari** [comment] 2019-07-05 18:43
Ok so I finally understand it now. It is a race between the notification handle and the startup procedure.

First, here's when the trip actually ended

```
5148,1562318519.678,2019-07-05 11:21:59.678000+00:09,TripDiaryStateMachineService : TripDiaryStateMachineReceiver handleTripEnd(local.transition.stopped_moving) called
```

Here's where the user clicked on the notification to launch the app. We finish the native code init 

```
5313,1562319983.776,2019-07-05 11:46:23.776000+00:09,UnifiedLogger : finished init of android native code
5317,1562319986.74,2019-07-05 11:46:26.740000+00:09,js : ionicPlatform is ready
5318,1562319986.7489998,2019-07-05 11:46:26.749000+00:09,js : about to get connection config
5319,1562319986.8620002,2019-07-05 11:46:26.862000+00:09,js : ionicPlatform.ready() called 0 times!
```

And are about to navigate to the start tab

```
5320,1562319986.869,2019-07-05 11:46:26.869000+00:09,js : About to navigate to preferred tab
```

Before we do so, notification code is triggered in parallel, which triggers the state change to the tripconfirm view

```
5339,1562319987.072,2019-07-05 11:46:27.072000+00:09,"js : Notification, click event"
5340,1562319987.079,2019-07-05 11:46:27.079000+00:09,"js : About to display completed trip from notification {""end_ts"":1562318503.874,""end_lat"":43.5220512,""end_lng"":5.4208097,""start_ts"":1562316393,""start_lat"":43.5142,""start_lng"":5.4624383}"
```

and then we return to the preferred tab determination code

```
5349,1562319987.2120001,2019-07-05 11:46:27.212000+00:09,BuiltinUserCache : Args =  type = 'local-storage' AND key = 'referral_navigation'
5350,1562319987.217,2019-07-05 11:46:27.217000+00:09,"BuiltinUserCache : in removeLocalStorage, deleted 0 document entries"
```

Aha! you think - I have found the race. The preferred tab overrides the `$state.go` from the tripconfirm. But we were smart and handled that already. We set the `rootScope.displayingIncident` to true and that causes the preferred screen logic to pick the tripconfirm state.

```
5351,1562319987.2220001,2019-07-05 11:46:27.222000+00:09,js : Showing tripconfirm from startprefs
5352,1562319987.232,2019-07-05 11:46:27.232000+00:09,js : changing state to root.main.tripconfirm
```

So what's the problem? The startprefs code does not pass in trip parameters. So the `$stateParams` are null and we hit this bug. It only happens if the notification handling code wins the race - if it loses, then it calls `$state.go` with the `stateParams` and everything works.

**Comment by shankari** [comment] 2019-07-05 19:52
Obvious fix is to pass through the parameters in the `$rootScope` and use them in the startprefs code as well.

**Comment by PatGendre** [comment] 2019-07-08 06:21
@shankari Hi, thanks for the explanation, this is a good cas study for a concurrent programming course :-)
I confirm that the 1/1/70 date is displayed when clicking on the post trip notification opens up the app ; when the app is already opened, the correct is displayed. @DO3B We will test your correction today.

**Comment by shankari** [comment] 2019-07-08 16:27
report from @PatGendre that @DO3B has sometimes clicked on the notification and NOT had the post-trip map display show up. Let's think through the race to see if we have covered all corner cases and whether there is anything else we need to fix.

The current implementation covers most of the conditions but I think that there is still a small race.

The current startprefs code looks like this

```
      startprefs.getNextState().then(changeState).catch(function(error) {
```

- if the notification code runs before the if check `          } else if ($rootScope.tripConfirmParams) {` called in `getNextState` then we are fine because `$rootScope.tripConfirmParams` is set and we will return `'root.main.tripconfirm'`
- if the notification code runs after the `$state.go(destState.state, destState.params).then(function() {` line in `changeState`, we are fine because then the notification `$state.go` will run after it and be the one that "sticks"

But if the notification code runs between those two, we might still have a race that causes the tripconfirm `state.go` transition to be overridden by the startprefs state transition.

Unfortunately, I can't think of a simple fix. This is javascript, so it is inherently multi-threaded, and the two threads are not related, so we can't use promises to coordinate between them.

**Comment by PatGendre** [comment] 2019-07-08 17:42
@shankari Ok thanks for having investigated the behaviour observed by Loic (@DO3B).
In practice regarding the survey notification, this is not a problem if some notifications happens not to be displayed, as the user can see all active surveys in the Surveys screen.

And regarding the 1970 date, I've tried once, and clicked on the notification before opening the app, and this time the correct today's date was displayed. So this is promising :-) I'll tell you if I see this '70 screen again but it is not likely.
However, there is something unusual, but I don't think it is related to the fix. After filling the mode/purpose info from the post trip notification, I clicked on the diary tab and I have this error
`while reading data from cache ... cannot read property 'data'`

![Screenshot_2019-07-08-19-38-59](https://user-images.githubusercontent.com/5039447/60830758-38c50080-a1b8-11e9-9319-734d5354ca4a.png)

So nothing is displayed in today's diary (instead of a draft trip)

**Comment by shankari** [comment] 2019-07-08 18:38
Couple of thoughts on this to ponder for now:
- the more I think about this, the less I am convinced that using `$rootScope` to coordinate between the two threads is a good idea. Might be worthwhile to see whether we can determine whether this is a trip confirmation on the startup thread directly
- An alternative approach might be to aim for eventual consistency. The main consistency issue is that we navigate away from the tripconfirm state when we go through the startup script. If we hook into the tripconfirm state change logic, we may be able to prevent that, or move back to the tripconfirm state or something like that.

**Comment by shankari** [comment] 2019-07-08 18:40
@PatGendre 

>  However, there is something unusual, but I don't think it is related to the fix. After filling the mode/purpose info from the post trip notification, I clicked on the diary tab and I have this error

this error is the same as #417 
I added some additional logging to help debug that; if you send me your logs again, I can take a look
Also, apparently, running the pipeline resolves the issue.

**Comment by shankari** [comment] 2019-07-08 18:47
But if it turns out that it was a server data issue, might want to hold off on running the pipeline until I have investigated the error.

**Comment by PatGendre** [comment] 2019-07-09 06:55
Hi @shankari , thanks for your help, here is the log
actually I didn't see any "sens length 532" in the file, but it might also related to the "check sensed data" button in the profile as both Loïc and I tested it.
[loggerDB0907.gz](https://github.com/e-mission/e-mission-docs/files/3371555/loggerDB0907.gz)

We tried to reset and run the pipeline for Loïc but it failed, because of another error presumably, in the cleaning and resampling pipeline stage  :
  ```
File "/var/emission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 1157, in _fix_squished_place_mismatch
    assert(min(section_counts) == 1)
AssertionError
```
So for the moment I prefer not resetting my pipeline...

**Comment by PatGendre** [comment] 2019-07-16 08:08
@shankari FYI I could reset and rerun the pipeline for Loïc and in the end it worked (except that for a section the mode is unknown). I described [here](https://github.com/e-mission/e-mission-docs/issues/251#issuecomment-509934444) sorry if this across 2 issues.

**Comment by shankari** [comment] 2019-07-16 16:03
@PatGendre no worries. Have you seen the 1/1/70 issue or any other tripconfirm issues recently? If not, can I merge the fixes and close this issue?

**Comment by PatGendre** [comment] 2019-07-16 16:35
@shankari no I didn't so you can merge the fixes and close.

**Comment by shankari** [comment] 2019-07-16 16:56
Closing this for now since https://github.com/e-mission/e-mission-phone/pull/596 seems to largely fix it.

**Closed by shankari** 2019-07-16 16:56 UTC
Labels: bug
