### ISSUE TITLE
stuck in the Current Trip

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#321] opened 2019-02-26 09:14 UTC
Hi, following our call of yesterday, please find attached the dump for the Feb 22 for the user who remains on the Current Trip on the diary screen since that day.
In case it helps, I may have switched location on and off, also, this is on an android 5 phone.
Besides, I have sometimes an "error 1000 while creating geofence", I don't what this means and if there can be a link with the issue.
[2019-02-22.2019-02-22.timeline.tar.gz](https://github.com/e-mission/e-mission-docs/files/2904617/2019-02-22.2019-02-22.timeline.tar.gz)

Thanks in advance if you can have a look and solve the issue:-)

**Comment by shankari** [comment] 2019-02-26 21:33
Yes, "error 1000 while creating geofence" is definitely related to turning location services off and on, https://github.com/e-mission/e-mission-data-collection/issues/127#issuecomment-287514412

Did you see this as a notification? That is the result of my initial attempt at fixing this, which was obviously not good/clear enough. I'm taking a look at the logs to see if there is anything else - I will put the logs related to my findings here as an example of how to debug such issues in the future.

As described in the troubleshooting section
https://github.com/e-mission/e-mission-docs/blob/a7d650349583f0dd35bfd7edf55bca784491f413/docs/e-mission-phone/troubleshooting_tips_faq.md#reading-the-log-on-your-computer
I will first convert the emailed log from the phone (that @PatGendre sent to me via email yesterday) to a text log file.

**Comment by shankari** [comment] 2019-02-26 22:54
The log has data from the 22nd to the 25th 

```
0,1550845305.918,2019-02-22 06:21:45.918000-07:53,"DataCollectionPlugin : google play services available, initializing state machine"
11748,1551113198.792,2019-02-25 08:46:38.792000-07:53,BuiltinUserCache : Added value for key background/motion_activity at time 1.551113198785E9
```

Let's look at the transitions generated by the FSM and received by the
broadcast receiver.

Here's the first trip.

```
1596,1550852970.5479999,2019-02-22 08:29:30.548000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@80fbf19, Intent { act=local.transition.exited_geofence flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
1957,1550853309.9520001,2019-02-22 08:35:09.952000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@80fbf19, Intent { act=local.transition.stopped_moving flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver (has extras) }) called"
```

Here's where the second trip starts

```
2005,1550853537.7810001,2019-02-22 08:38:57.781000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@80fbf19, Intent { act=local.transition.exited_geofence flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
```

and then we get an initialize message generated from rebooting while in
`ongoing_state` state, and pass them on to the service that does the actual
work

```
3348,1550903464.783,2019-02-22 22:31:04.783000-07:53,BootReceiver : BootReceiver.onReceive called
3350,1550903479.322,2019-02-22 22:31:19.322000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@1fdd81c5, Intent { act=local.transition.initialize flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
3360,1550903479.764,2019-02-22 22:31:19.764000-07:53,"TripDiaryStateMachineService : handleAction(local.state.ongoing_trip, local.transition.initialize) calle"
3362,1550903479.815,2019-02-22 22:31:19.815000-07:53,TripDiaryStateMachineService : TripDiaryStateMachineReceiver handleStarted(local.transition.initialize) called
```

Since we have no idea what state we should be in, we just restart the FSM by trying to create a geofence. But the last location is null, so we try to read the location.

```
3364,1550903479.856,2019-02-22 22:31:19.856000-07:53,"CreateGeofenceAction : mLastLocationTime = null, launching callback to read it and thencreate the geofence"
3367,1550903479.9129999,2019-02-22 22:31:19.913000-07:53,CreateGeofenceAction : About to start waiting for location
```

That location was also null, with `EXTRA_LOCATION_AVAILABILITY`, which is
consistent with the location services being turned off.
https://github.com/e-mission/e-mission-data-collection/issues/127#issuecomment-464477968

```
3370,1550903479.974,2019-02-22 22:31:19.974000-07:53,GeofenceLocationIntentService : Extras keys are [com.google.android.gms.location.EXTRA_LOCATION_AVAILABILITY]
3371,1550903479.986,2019-02-22 22:31:19.986000-07:53,GeofenceLocationIntentService : Read location null from intent
```

Next update was again caused by the reboot and we again got a null update

```
3399,1550920562.09,2019-02-23 03:16:02.090000-07:53,BootReceiver : BootReceiver.onReceive called
3401,1550920597.188,2019-02-23 03:16:37.188000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@22178c31, Intent { act=local.transition.initialize flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
3421,1550920598.0279999,2019-02-23 03:16:38.028000-07:53,GeofenceLocationIntentService : Extras keys are [com.google.android.gms.location.EXTRA_LOCATION_AVAILABILITY]
3422,1550920598.0839999,2019-02-23 03:16:38.084000-07:53,GeofenceLocationIntentService : Read location null from intent
```

and this time we were actually woken up correctly and generated an error notification

```
3457,1550922260.824,2019-02-23 03:44:20.824000-07:53,"CreateGeofenceAction : After waiting for location reading result, location is null"
3458,1550922260.9689999,2019-02-23 03:44:20.969000-07:53,"CreateGeofenceAction : Was not able to read new location, skipping geofence creation"
```

And then we see the same pattern for a while

```
3659,1550992126.062,2019-02-23 23:08:46.062000-07:53,BootReceiver : BootReceiver.onReceive called
3661,1550992164.9160001,2019-02-23 23:09:24.916000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@23873029, Intent { act=local.transition.initialize flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
3682,1550992165.72,2019-02-23 23:09:25.720000-07:53,GeofenceLocationIntentService : Read location null from intent
3683,1550992765.66,2019-02-23 23:19:25.660000-07:53,"CreateGeofenceAction : After waiting for location reading result, location is null"

...


3739,1550998379.435,2019-02-24 00:52:59.435000-07:53,BootReceiver : BootReceiver.onReceive called
3741,1550998393.64,2019-02-24 00:53:13.640000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@19f96fc, Intent { act=local.transition.initialize flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
3762,1550998394.295,2019-02-24 00:53:14.295000-07:53,GeofenceLocationIntentService : Read location null from intent
3792,1550998994.1039999,2019-02-24 01:03:14.104000-07:53,"CreateGeofenceAction : After waiting for location reading result, location is null"
```

**Comment by shankari** [comment] 2019-02-26 23:49
Starting from the end to see when the pattern changed...

Apparently, tracking was toggled. But because the state was already
'ongoing_trip', we didn't have to do anything special while starting tracking.
I wonder if the state of the tracking/non-tracking button was broken in this case.

```
7750,1551100257.579,2019-02-25 05:10:57.579000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@2a6a78f8, Intent { act=local.transition.start_tracking flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
7768,1551100257.8539999,2019-02-25 05:10:57.854000-07:53,"TripDiaryStateMachineService : handleAction(local.state.ongoing_trip, local.transition.start_tracking) calle"
```

Before this, we got an `exited_geofence` transition, which first got null, but
then got some actual location points.

```
4380,1551077660.967,2019-02-24 22:54:20.967000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@a19606a, Intent { act=local.transition.exited_geofence flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
4408,1551077667.0770001,2019-02-24 22:54:27.077000-07:53,LocationChangeIntentService : Read location null from intent
4414,1551077667.776,2019-02-24 22:54:27.776000-07:53,"LocationChangeIntentService : Read location Location[fused 43,519024,5,469430 acc=17 et=+55m30s950ms alt=243.5 {Bundle[mParcelledData.dataSize=52]}] from intent"
4450,1551077689.17,2019-02-24 22:54:49.170000-07:53,"LocationChangeIntentService : Read location Location[fused 43,519032,5,469629 acc=14 et=+55m53s158ms alt=248.60000610351563 {Bundle[mParcelledData.dataSize=52]}] from intent"
```

And before that, there was a reboot and the same pattern initially

```
4236,1551074424.304,2019-02-24 22:00:24.304000-07:53,BootReceiver : BootReceiver.onReceive called
4238,1551074437.6929998,2019-02-24 22:00:37.693000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@1e8e35ee, Intent { act=local.transition.initialize flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
4259,1551074438.437,2019-02-24 22:00:38.437000-07:53,GeofenceLocationIntentService : Read location null from intent
```

But soon after that, it looks like LocationServices was turned on, and we got a update which caused the FSM to go to `WAITING_FOR_TRIP_START`

```
4296,1551077373.946,2019-02-24 22:49:33.946000-07:53,GeofenceLocationIntentService : onStart called with Intent { cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.actions.GeofenceLocationIntentService (has extras) } startId 1
4300,1551077374.03,2019-02-24 22:49:34.030000-07:53,"GeofenceLocationIntentService : Read location Location[fused 43,519533,5,467455 acc=14 et=+50m28s665ms alt=229.5 {Bundle[mParcelledData.dataSize=52]}] from intent"
4306,1551077374.3620002,2019-02-24 22:49:34.362000-07:53,TripDiaryStateMachineService : newState after handling action is local.state.waiting_for_trip_start
```

and then we got an exited_geofence (the first transition above), which of
course, put it back into ONGOING_TRIP

```
4380,1551077660.967,2019-02-24 22:54:20.967000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@a19606a, Intent { act=local.transition.exited_geofence flg=0x10 cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
```

Let us see how many location points we got after this. We got one with
availability = true, but fairly soon after that, availability went back to
false (location services turned off again?) and so the FSM was stuck again.

```
4409,1551077667.089,2019-02-24 22:54:27.089000-07:53,LocationChangeIntentService : availability = true
4936,1551077928.1820002,2019-02-24 22:58:48.182000-07:53,LocationChangeIntentService : availability = false
2430,1550854088.331,2019-02-22 08:48:08.331000-07:53,"LocationChangeIntentService : location is not available, move to start state?"
```

**Comment by shankari** [comment] 2019-02-26 23:51
As far as I can tell from the logs, all issues seem to be related to the availability of location services. So this is a duplicate of https://github.com/e-mission/e-mission-data-collection/issues/127

@PatGendre please test the apk with the fix uploaded to that issue.

**Comment by shankari** [comment] 2019-02-27 00:21
Couple of other comments:
here's where the current screen is launched - if you want to remove it or modify it
https://github.com/e-mission/e-mission-phone/blob/master/www/js/metrics.js#L24

It should really go into 
https://github.com/e-mission/e-mission-phone/blob/master/www/js/splash/startprefs.js#L165

but the student who implemented it submitted it at the end of the semester https://github.com/e-mission/e-mission-phone/commit/321c86d2424236f1d6f836c4c59bbead4c516094  and was not going to continue, so I merged it anyway.

**Comment by shankari** [comment] 2019-02-27 00:21
Closing as duplicate of https://github.com/e-mission/e-mission-data-collection/issues/127

**Closed by shankari** 2019-02-27 00:21 UTC
