### ISSUE TITLE
Blank label Screen on staging

### ISSUE THREAD

**Issue by Abby-Wheelis** [e-mission/e-mission-docs#971] opened 2023-09-07 22:54 UTC
A few times today, on my test iPhone, I've seen a behavior where the label screen will go completely blank, but the dashboard is fine and can be refreshed. Closing and reopening the app does not resolve the issue, but reinstalling did. I've seen this off and on working on the dashboard (a branch up to date with what's on staging) and there were console errors about "loc_geojson.coordinates" and "locationPoint.coordinates" being undefined. I've yet to reproduce on the staging branch in the emulator, so not real debugging yet.

Starting an issue to track when I encounter this and see if I can reproduce in the emulator.

**Comment by Abby-Wheelis** [comment] 2023-09-07 22:56
Most recent occurrence: 

- opened app to label trips, was offline
- connected to wifi
- opened app, loading spun briefly then screen went blank
- confirmed dashboard refreshed, so phone is online
- closed and reopened app, same issue
- logged in with that opcode on `label_dashboard_profile_sept_2023` (staging branch)
- label screen loaded and I had a trip ready to label

**Comment by shankari** [comment] 2023-09-07 23:07
> logged in with that opcode on label_dashboard_profile_sept_2023 (staging branch)

So the test iPhone is not on staging? Or was this in the emulator?

**Comment by Abby-Wheelis** [comment] 2023-09-07 23:11
>So the test iPhone is not on staging? Or was this in the emulator?

Test iPhone is on staging (with TestFlight) and using a `nrelop_stage-program_test_` opcode. After encountering the issue on the test iPhone, I tried the same opcode in the emulator, and failed to reproduce. So 1-5 was on the test iPhone with staging and 6-7 was with the same opcode in the emulator.

**Comment by shankari** [comment] 2023-09-07 23:15
could this be another dev build versus prod build issue?

**Comment by Abby-Wheelis** [comment] 2023-09-07 23:17
Maybe... but 

> I've seen this off and on working on the dashboard (a branch up to date with what's on staging) and there were console errors about "loc_geojson.coordinates" and "locationPoint.coordinates" being undefined. 

Not today, but yesterday. I'll document and debug if I catch it in the emulator again. Since I was happening off and on I thought it might be a devapp quirk until I encountered it on a real phone.

**Comment by JGreenlee** [comment] 2023-09-08 03:23
<img width="798" alt="image" src="https://github.com/e-mission/e-mission-docs/assets/15843932/9cc31863-c7f6-406c-a0ce-feb04978f0e3">

**Comment by JGreenlee** [comment] 2023-09-08 03:25
It's as I suspected - the `start_loc` and `end_loc` of this draft trip are undefined:

<img width="364" alt="image" src="https://github.com/e-mission/e-mission-docs/assets/15843932/7e3e7b64-1fda-411b-bb12-51a1a2390710">

But why?

**Comment by JGreenlee** [comment] 2023-09-08 03:42
I traced this back to where unprocessed trips are constructed and looked for this log statement: https://github.com/e-mission/e-mission-phone/blob/d6637a6e4f9978d626c0374a838582e4aacb23f3/www/js/diary/services.js#L252

Found one:
```
DEBUG:tripStartPoint = {"metadata":{"write_ts":1694141584.263,"key":"background/filtered_location","time_zone":"America/New_York","type":"sensor-data","read_ts":0,"platform":"android"},"data":{"filter":"time","longitude":-84.3922145,"elapsedRealtimeNanos":267595899654183,"bearing":0,"sensed_speed":0,"ts":1694141584.151,"latitude":39.3241168,"accuracy":5.481,"fmt_time":"Sep 7, 2023 22:53:04","altitude":191},"_id":{"$oid":"64fa8d9b6109165fe7062db0"},"user_id":{"$uuid":"71d6fa29f5964b3a920e67680f423537"}}tripEndPoint = {"metadata":{"write_ts":1694141848.285,"key":"background/filtered_location","time_zone":"America/New_York","type":"sensor-data","read_ts":0,"platform":"android"},"data":{"filter":"time","longitude":-84.3922398,"elapsedRealtimeNanos":267858885587489,"bearing":37.864338,"sensed_speed":0.18522134,"ts":1694141847.138,"latitude":39.3242076,"accuracy":31.087,"fmt_time":"Sep 7, 2023 22:57:27","altitude":187.91500005353993},"_id":{"$oid":"64fa8d9b6109165fe7062dce"},"user_id":{"$uuid":"71d6fa29f5964b3a920e67680f423537"}}
```

Let's clean that up a bit to see what's inside `tripStartPoint`:
```json
{
  "metadata": {
    "write_ts": 1694141584.263,
    "key": "background/filtered_location",
    "time_zone": "America/New_York",
    "type": "sensor-data",
    "read_ts": 0,
    "platform": "android"
  },
  "data": {
    "filter": "time",
    "longitude": -84.3922145,
    "elapsedRealtimeNanos": 267595899654183,
    "bearing": 0,
    "sensed_speed": 0,
    "ts": 1694141584.151,
    "latitude": 39.3241168,
    "accuracy": 5.481,
    "fmt_time": "Sep 7, 2023 22:53:04",
    "altitude": 191
  },
  "_id": {
    "$oid": "64fa8d9b6109165fe7062db0"
  },
  "user_id": {
    "$uuid": "71d6fa29f5964b3a920e67680f423537"
  }
}
```

There is no `data.loc`, which is what we look for to use as `trip.start_loc`: https://github.com/e-mission/e-mission-phone/blob/d6637a6e4f9978d626c0374a838582e4aacb23f3/www/js/diary/services.js#L268


The very next unprocessed trip that gets logged out *does* have a `data.loc` in its `tripStartPoint`:
```json
{
  "metadata": {
    "time_zone": "America/New_York",
    "write_ts": 1694123597.698,
    "write_local_dt": {
      "minute": 53,
      "hour": 17,
      "second": 17,
      "day": 7,
      "weekday": 3,
      "month": 9,
      "timezone": "America/New_York",
      "year": 2023
    },
    "platform": "android",
    "read_ts": 0,
    "write_fmt_time": "2023-09-07T17:53:17.698000-04:00",
    "key": "background/filtered_location",
    "type": "sensor-data"
  },
  "data": {
    "heading": 0,
    "local_dt": {
      "minute": 53,
      "hour": 17,
      "second": 17,
      "day": 7,
      "weekday": 3,
      "month": 9,
      "timezone": "America/New_York",
      "year": 2023
    },
    "longitude": -84.3922509,
    "sensed_speed": 0,
    "latitude": 39.3241956,
    "fmt_time": "2023-09-07T17:53:17.636000-04:00",
    "elapsedRealtimeNanos": 249609383000000,
    "filter": "time",
    "accuracy": 20.096,
    "loc": {
      "type": "Point",
      "coordinates": [
        -84.3922509,
        39.3241956
      ]
    },
    "altitude": 191,
    "ts": 1694123597.636
  },
  "_id": {
    "$oid": "64fa4736610916272b59b44a"
  },
  "user_id": {
    "$uuid": "71d6fa29f5964b3a920e67680f423537"
  }
}
```

**Comment by JGreenlee** [comment] 2023-09-08 03:47
This suggests a discrepancy in sensor data, which is weird.

But I doubt the discrepancy is a new phenomenon. The issue probably existed silently before, but throws an error now that geojson creation was moved into a React hook.

**Comment by JGreenlee** [comment] 2023-09-08 03:53
Probably related: I have previously observed draft trips missing their start and end markers, and this was documented by someone else [at least once](https://github.com/e-mission/e-mission-docs/issues/953#issuecomment-1685120741).

**Comment by JGreenlee** [comment] 2023-09-08 03:59
If need be, there is a pretty clear workaround for this - `loc` isn't present in the first sensor data entry but it does have `latitude` and `longitude`. So we could easily just construct the needed coordinates as `[latitude, longitude]`

But before doing that and moving on, I'd prefer to have a better understanding of why there is any discrepancy at all in the sensor data.

**Comment by shankari** [comment] 2023-09-08 05:28
I saw a similar, but weirder issue that may or may not be related.
The "To Label" screen works (and worked) but the "All Trips" shows a blank. I also don't see any error displayed when I go to "All Trips"

| to label not blank even with draft trips | to label not blank | All trips blank |
|------|------|-----|
| ![all_trips_blank](https://github.com/e-mission/e-mission-docs/assets/2423263/451da3e7-8134-43e4-ae5c-217cbed850dc) | ![to_label_not_blank](https://github.com/e-mission/e-mission-docs/assets/2423263/9d9399a8-0829-4055-b9b6-7e0040060ca0) | ![to_label_not_blank_even_with_draft](https://github.com/e-mission/e-mission-docs/assets/2423263/33dec48a-0873-4108-8220-7e42f5aec122) |

**Comment by shankari** [comment] 2023-09-08 05:50
> But before doing that and moving on, I'd prefer to have a better understanding of why there is any discrepancy at all in the sensor data.

I am 99% sure that this is because of different levels of processing of the draft sensor data.
The `data.loc` and `data.local_dt` and `metadata.write_ts` fields are added when the data arrives at the server (e.g. https://github.com/e-mission/e-mission-server/blob/94e7478e627fa8c171323662f951c611c0993031/emission/net/usercache/formatters/android/location.py#L47)

So it looks like the first point from https://github.com/e-mission/e-mission-docs/issues/971#issuecomment-1711031906, which doesn't have any of those, is a point that has been sensed, but not yet pushed up to the server, or is still in the usercache and has not passed through the formatter. The second point is one that has passed through the formatter (aka passed the `moveToLongTerm` pipeline stage).

Before this change https://github.com/e-mission/e-mission-phone/commit/67f40f20afb6ee117196a5d8a1a62d19e12ea200 we created the unprocessed trips geojson by using `place2Geojson`, which used `latitude` and `longitude` to construct the geojson point. 

After the change, we use `data.loc` to return the trip properties, which will be converted to geojson down the road. But the `data.loc` won't exist for points that have not yet been pushed to the server.

Note that this will not occur on the emulator because we are typically not sensing any points on the emulator - we only read data that has already been pushed to the server (but may not have been fully processed). But on a real phone, we are actually sensing points on the device, so we can have completely unprocessed points, which don't have a `data.loc`

**Comment by JGreenlee** [comment] 2023-09-08 17:00
> The "To Label" screen works (and worked) but the "All Trips" shows a blank. I also don't see any error displayed when I go to "All Trips"
> To reproduce, use the opcode for "Android LG (Tom's old phone)" from the internal wiki

I tried to reproduce this today but could not. (This makes me wonder if it is related to draft trips after all)



> @JGreenlee as a general note, I am not sure that we kept all the tools for system-level debugging during the rewrite

Certainly, there are a lot of things that changed during the rewrite and it was not always easy to keep those debugging tools integrated while bridging between Angular + React. I think now that the bulk of our code is in React, we can go back over what we missed. 

> Before this change [e-mission/e-mission-phone@67f40f2](https://github.com/e-mission/e-mission-phone/commit/67f40f20afb6ee117196a5d8a1a62d19e12ea200) we created the unprocessed trips geojson by using `place2Geojson`, which used `latitude` and `longitude` to construct the geojson point.
> 
> After the change, we use `data.loc` to return the trip properties, which will be converted to geojson down the road. But the `data.loc` won't exist for points that have not yet been pushed to the server.

Thank you for clarifying. This makes sense. When I fix this, I will ensure that we don't rely on `loc` and instead we will construct it with [`longitude, latitude]` like before.

**Comment by shankari** [comment] 2023-09-11 02:36
I can verify that this seems to be fixed with the changes in https://github.com/e-mission/e-mission-phone/pull/1026

I just came back after taking some trips, and:

| Saw blank screen | Updated app | Saw draft trips |
|-------|--------|-------|
| ![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/16170219-0f20-4e4e-ad5a-f413d180b27b) | ![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/28674f4d-4dff-4207-870e-09172be57c8f) | ![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/4e0eed9a-6c68-4463-a5f7-5e4bfb883646) |

**Closed** 2023-09-12 13:50 UTC
