### ISSUE TITLE
Not working: toggle switch for aggregate metrics

### ISSUE THREAD

**Issue by niccolopaganini** [e-mission/e-mission-docs#957] opened 2023-08-23 20:57 UTC
During my testing for android 13 in Google Pixel 4a, I noticed that the toggle switch for aggregate metrics is not working.
The toggle switch I am referring to is under the chart section of the dashboard window. I have attached a video for reference and to showcase the problem at hand. 

https://github.com/e-mission/e-mission-docs/assets/69108657/4528558d-1786-4adf-a6dc-9e535d895838

**Comment by shankari** [comment] 2023-08-24 00:49
I can confirm that this works on my personal phone, so definitely a regression.
Marking this as a showstopper.
Good job finding it @niccolopaganini - you have been very thorough in the testing.

**Comment by JGreenlee** [comment] 2023-08-24 01:15
I haven't been able to reproduce it on either iOS or Android.
I'll try `serve-prod` to see if it's (yet another) production-specific bug.

**Comment by JGreenlee** [comment] 2023-08-24 19:08
I still have not been able to reproduce this issue.
@niccolopaganini On what OPCode did you experience this issue? Can you try a different one to see if it is OPCode-specific?

**Comment by shankari** [comment] 2023-08-24 19:15
Could it be an android 13 issue?
@niccolopaganini are you seeing it on android 12 as well?

**Comment by shankari** [comment] 2023-08-25 03:56
@JGreenlee I just spoke to @niccolopaganini and he is seeing the same issue on android 13 and android 10 and android 11 with the same opcode.

**Comment by shankari** [comment] 2023-08-25 04:11
I just spoke to @niccolopaganini and before the error with the aggregate metrics, he got errors on the dashboard around "undefined". So that's why nothing shows up - because the data load essentially failed. That is why all the numbers are zero and the user and aggregate values are blank.

So this is essentially the bug fixed by @Abby-Wheelis - I have not pushed it to staging while waiting to see if there are any other changes we need to batch up.

**Comment by shankari** [comment] 2023-08-25 04:12
Closing as a dup of https://github.com/e-mission/e-mission-docs/issues/947

**Closed by shankari** 2023-08-25 04:12 UTC

**Comment by Abby-Wheelis** [comment] 2023-08-25 16:48
Confirmed this morning by logging into the opCode where the aggregate switched wasn't working that the issue was as suspected and everything is fine in the emulator with that fix in place!
