### ISSUE TITLE
Unable to build for Android (maybe certificate issue?)

### ISSUE THREAD

**Issue by JGreenlee** [e-mission/e-mission-docs#1093] opened 2024-09-26 18:23 UTC
I have been running into this issue which prevents me from building for Android.

Everything looks normal until:
```
> Task :wrapper FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wrapper'.
> Test of distribution url https://services.gradle.org/distributions/gradle-8.7-bin.zip failed. Please check the values set with --gradle-distribution-url and --gradle-version.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
1 actionable task: 1 executed
Command failed with exit code 1: gradle -p /Users/jgreenle/e-mission-phone/platforms/android/tools wrapper --gradle-version 8.7
```

I can see that the scripts install Gradle 8.10 successfully, but then attempt to download Gradle 8.7 (which fails for me but is successful in the CI)

This leads me to believe 2 things:
- Gradle 8.10 is not being used, neither on my setup or the CI
- Something on my machine causes the Gradle 8.7 download to fail (I am guessing certificates)

**Comment by shankari** [comment] 2024-09-27 20:46
> Gradle 8.10 is not being used, neither on my setup or the CI

This is true. The build should download its own gradle.
I actually removed the gradle install in https://github.com/e-mission/e-mission-phone/commit/399e9e7a4f83ed7d67fbf2e249179fa073cfec68

But then it turns out that if there is no system gradle, then the build fails so I restored it
https://github.com/e-mission/e-mission-phone/commit/3b6ecd5fda65ac8cae2bf9127a0789cc7fadb3c2

Have you pulled the changes for the upgrade and deleted all your existing setup? I remember there was a gradle issue during the upgrade that was fixed by upgrading android. And I had to delete all platforms and plugins after the upgrade.

**Comment by JGreenlee** [comment] 2024-09-30 15:53
I am able to reproduce this on a freshly cloned repo, so I don't think it is the issue you described.
I have also tried reinstalling the Android SDK to no avail.

**Comment by shankari** [comment] 2024-12-09 16:47
I am able to reproduce this on my new M3 laptop.
Spending a time-bounded amount on this so that I can generate a new release, although I will stop after a few hours because the highest-priority changes are all on iOS.

**Comment by shankari** [comment] 2024-12-09 17:06
the java root certs are installed in [`JAVA_HOME /lib/security`] (https://docs.oracle.com/javase/9/tools/keytool.htm#GUID-5990A2E4-78E3-47B7-AE75-6D1826259549__CACERTS)

**Comment by shankari** [comment] 2024-12-09 17:41
while waiting for my older x86 laptop to start turning on, I checked the netskope documentation to see if the netskope root CA is available to java, and it is.

Per https://community.netskope.com/next-gen-swg-2/configuring-cli-based-tools-and-development-frameworks-to-work-with-netskope-ssl-interception-7015, the netskope root CA is at `/Library/Application Support/Netskope/STAgent/data/nscacert_combined.pem`

which, using `$ openssl x509 -in /Library/Application\ Support/Netskope/STAgent/data/nscacert.pem -fingerprint -sha256` has the same signature as `certadmin-netskope inc.-0138`

So the root CA should be recognized.

**Comment by shankari** [comment] 2024-12-09 17:43
There were some comments about gradle potentially using the wrong root CA
But I set `JAVA_HOME` correctly and it still didn't work

```
$ /usr/libexec/java_home
$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by shankari** [comment] 2024-12-09 17:50
I also found https://discuss.gradle.org/t/bypass-ssl-certification/21447/6

> Adding our Webfiltering root CA certificate to Android Studio resolved all cert errors except for Gradle, we even tried ticking the ‘accept non-trusted certificates automatically’ but still had issues with Gradle?
> In an attempt to resolve it I disabled SSL inspection for [https://services.gradle.org/](https://services.gradle.org/?_gl=1*1yzy4nt*_gcl_au*MTk3NTI1NDg2MS4xNzMzNzY2Mjgy*_ga*Mjk0OTQ2MDQuMTczMzc2NjI4Mg..*_ga_7W7NC6YNPT*MTczMzc2NjI4MS4xLjEuMTczMzc2NjQzNy42MC4wLjA.&_ga=2.264553542.818720340.1733766282-29494604.1733766282) (location of what studio wanted to access) but this didn’t resolve the issue. After much messing around I spotted that https://services.gradle.org/ certificate is actually issued to [ssl473435.cloudflaressl.com](http://ssl473435.cloudflaressl.com/) rather than itself? Not sure how this passes validation in browser but it does. Anyhow adding this as an SSL inspection exception resolved the issue for us. I don’t know if this is something gradle can change to reduce issues with cooperate entities & improved support for Android Studio’s settings.

and that is when I noticed that the error was indeed while downloading the gradle zip file

```
Downloading https://services.gradle.org/distributions/gradle-8.7-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Checking to see if I can manually download the file and then point to a `file` URL instead

**Comment by shankari** [comment] 2024-12-09 18:23
I instead tried to download to gradle 8.7

```
Installing: gradle 8.7
Done installing!
Setting gradle 8.7 as default.
```

which then fails the "test of the distribution URL"

```
> Test of distribution url https://services.gradle.org/distributions/gradle-8.7-bin.zip failed. Please check the values set with --gradle-distribution-url and --gradle-version.
```

We need to:
- change the distribution URL (and have a locally cached version), OR
- disable the test of the distribution URL

Let's try for (2) first.

**Comment by shankari** [comment] 2024-12-09 18:49
Here the options to turn it off are `--no-validate-url`

Should be in gradle 8.7

As an aside, I don't understand why this is even trying for gradle 8.7 since the current version of android is supposed to use gradle 7.6

<img width="1126" alt="Screenshot 2024-12-09 at 10 45 28 AM" src="https://github.com/user-attachments/assets/c5d04502-9a3a-4391-9538-4507b258ee52">

**Comment by shankari** [comment] 2024-12-09 19:01
Looking at the cordova android source code in `node_modules//cordova-android/lib/builders/ProjectBuilder.js`, it looks like (1) is actually the easier option.

```
            events.emit('verbose', `Overriding Gradle Version via CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL (${process.env.CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL})`);
            await execa('gradle', ['-p', path.join(this.root, 'tools'), 'wrapper', '--gradle-distribution-url', process.env.CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL], { stdio: 'inherit' }); 
```

**Comment by shankari** [comment] 2024-12-09 19:30
Downloading via curl gives us

```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

So the verification failed with:

```
Downloading file:/Users/kshankar/bin/gradle-8.7-bin.zip
100%
Could not unzip /Users/kshankar/.gradle/wrapper/dists/gradle-8.7-bin/dupjvekv5jxb46q6vvp158dzi/gradle-8.7-bin.zip to /Users/kshankar/.gradle/wrapper/dists/gradle-8.7-bin/dupjvekv5jxb46q6vvp158dzi.
```

Switching to a manual download via the browser

```
$ mv ~/Downloads/gradle-8.7-bin.zip ~/bin/
```

```
$ export CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=file:///Users/kshankar/bin/gradle-8.7-bin.zip
```

got us further, but stuck again while downloading dependencies. We need to 

```
Could not fetch hash for file:/Users/kshankar/bin/gradle-8.7-bin.zip.
Reason: /Users/kshankar/bin/gradle-8.7-bin.zip.sha256 (No such file or directory)
Downloading file:/Users/kshankar/bin/gradle-8.7-bin.zip
............10%.............20%.............30%.............40%............50%.............60%.............70%.............80%.............90%............100%
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/kshankar/e-mission/native_code_upgrade/platforms/android/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'emission'.
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not resolve io.github.g00fy2:versioncompare:1.4.1.
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve io.github.g00fy2:versioncompare:1.4.1.
         > Could not get resource 'https://repo.maven.apache.org/maven2/io/github/g00fy2/versioncompare/1.4.1/versioncompare-1.4.1.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/io/github/g00fy2/versioncompare/1.4.1/versioncompare-1.4.1.pom'.
               > Got SSL handshake exception during request. It might be caused by SSL misconfiguration
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by shankari** [comment] 2024-12-09 20:19
confirmed that this is working fine on my old laptop; doing a side-by-side comparison...

- the cacerts has the same two netskope signatures
- both keystores contain 154 entries

I copied over the cacerts from my old laptop and they were different!

```
$ diff /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts.from_install 
Binary files /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts and /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts.from_install differ
$ diff /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts.from_old_laptop /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts.from_install 
Binary files /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts.from_old_laptop and /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts.from_install differ
```

Switching to the version from the old laptop

```
$ diff /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/security/cacerts.from_old_laptop
```

and restarting the gradle daemon, the build succeeded!

```
$ gradle -stop
```

@JGreenlee I am happy to send you the "working CA bundle". We should also follow up internally to understand the reason for the difference, but I think I have spent as much time as I am going to on this for now given the urgent need to get the next release out.

**Closed** 2024-12-09 20:20 UTC
