### ISSUE TITLE
Trips are not getting cleaned through the pipeline

### ISSUE THREAD

**Issue by valin1** [e-mission/e-mission-docs#439] opened 2019-07-24 03:16 UTC
```
Traceback (most recent call last):
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 284, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 229, in trip_to_geojson
    start_place_geojson = place_to_geojson(curr_start_place)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 76, in place_to_geojson
    ret_feature.id = str(place.get_id())
AttributeError: 'NoneType' object has no attribute 'get_id'
END 2019-07-22 22:31:48.631111 POST /timeline/getTrips/2019-07-21 f3dc99ea-889d-40f5-985b-b7c31093685f 0.05051684379577637 
Traceback (most recent call last):
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/net/api/bottle.py", line 1998, in wrapper
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 262, in getTrips
    ret_geojson = timeline.get_trips_for_day(user_uuid, day, force_refresh)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/net/api/timeline.py", line 41, in get_trips_for_day
    return gfc.get_geojson_for_dt(user_uuid, start_dt, end_dt)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 274, in get_geojson_for_dt
    return get_geojson_for_timeline(user_id, tl)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 289, in get_geojson_for_timeline
    raise e
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 284, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 229, in trip_to_geojson
    start_place_geojson = place_to_geojson(curr_start_place)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 76, in place_to_geojson
    ret_feature.id = str(place.get_id())
AttributeError: 'NoneType' object has no attribute 'get_id'
/Users/trevorwu/anaconda3/envs/emission/lib/python3.6/sre_parse.py:864: DeprecationWarning: Flags not at the start of the expression \{\{((?:(?mx)(       (truncated)
  p = _parse_sub(source, pattern, True, False)
START 2019-07-22 22:31:48.754707 POST /datastreams/find_entries/timestamp
```

Traceback of the errors regarding the pipeline but both the server and Trevor's emulator aren't cleaning my trips.

**Comment by valin1** [comment] 2019-07-24 03:19
https://github.com/e-mission/e-mission-server/blame/b004108a5335ba2a7cc79eee03c2c41be9f7b08a/emission/analysis/plotting/geojson/geojson_feature_converter.py

**Comment by shankari** [comment] 2019-07-24 04:39
@valin1 from the code, it looks like this is triggered when there is a trip with `start_place` = `None`, so `place.get_id()` is converted to `None.get_id()` which fails.

Are you sure this is the error on the server, or is this an error on @trevor-wu's laptop? Did you re-run the pipeline or only load the data? If you extract a **subset** of the data **including the analysis objects** from the server and don't reset the pipeline before re-running it, the first trip downloaded from the server will have a place that is not downloaded. So when we try to look up the place, we will get `None` and may encounter this error.

Please indicate the steps to reproduce as well.

**Comment by valin1** [comment] 2019-07-29 00:37
This is the error from the server 
``` 
  File "/new_disk/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 23, in predict_mode
    mip.runPredictionPipeline(user_id, time_query)
  File "/new_disk/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 51, in runPredictionPipeline
    self.predictedProb = self.predictModesStep()
  File "/new_disk/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 70, in predictModesStep
    predictedProb.append(get_prediction(i, section_entry))
  File "/new_disk/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 109, in get_prediction
    return get_motorized_prediction(i, section_entry)
  File "/new_disk/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 136, in get_motorized_prediction
    predicted_transit_mode = _get_transit_prediction(i, section_entry)
  File "/new_disk/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 162, in _get_transit_prediction
    start_transit_stops = enetm.get_stops_near(section_entry.data.start_loc, start_radius)
  File "/new_disk/e-mission-server/emission/net/ext_service/transit_matching/match_stops.py", line 65, in get_stops_near
    stops = get_public_transit_stops(lat - bbox_delta, lon - bbox_delta, lat + bbox_delta, lon + bbox_delta)
  File "/new_disk/e-mission-server/emission/net/ext_service/transit_matching/match_stops.py", line 30, in get_public_transit_stops
    all_results = response.json()["elements"]
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/site-packages/requests/models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by valin1** [comment] 2019-07-29 00:43
The steps to reproduce the error, I'm not exactly sure because I just downloaded my data from the app and sent them to Trevor.

**Comment by shankari** [comment] 2019-07-29 00:58
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Looks like a dup of #405 
Did you search the prior issues to see if there was a workaround?

**Comment by shankari** [comment] 2019-07-29 00:59
> The steps to reproduce the error, I'm not exactly sure because I just downloaded my data from the app and sent them to Trevor.

So this is almost certainly

> If you extract a subset of the data including the analysis objects from the server and don't reset the pipeline before re-running it,

**Comment by valin1** [comment] 2019-07-29 01:01
Actually, we checked the trips again and it seemed like they're clean now, but we are still checking with Trevor if the dropbar for destination works locally.

**Comment by shankari** [comment] 2019-07-29 01:07
In that case, this is almost certainly a dup of #405, which, if you see, is an intermittent issue caused by too many calls to the overpass API in quick succession. Closing this; please open a new issue for the dropbar if it turns out to be related to my code.

**Closed by shankari** 2019-07-29 01:07 UTC

**Comment by shankari** [comment] 2019-07-29 02:28
@valin1 @ecvick85 you might want to apply the workarounds listed in #405 before you start the study
