### ISSUE TITLE
Analyis Pipeline does not result in updated trips on phone

### ISSUE THREAD

**Issue by jf87** [e-mission/e-mission-docs#316] opened 2019-02-13 10:29 UTC
I have setup an e-mission server. I run the intake pipeline as suggested in the docs:
`cd /home/ubuntu/src/e-mission-server && PYTHONPATH=. /home/ubuntu/anaconda3/envs/emission/bin/python bin/intake_multiprocess.py 3
`
This seems to run smoothly:

`2019-02-12T17:18:58.663809+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: moving to long term**********
2019-02-12T17:18:58.671613+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: moving to long term**********
2019-02-12T17:18:58.675298+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: moving to long term**********
2019-02-12T17:18:58.682250+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: filter accuracy if needed**********
2019-02-12T17:18:58.684055+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: filter accuracy if needed**********
2019-02-12T17:18:58.691202+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into trips**********
2019-02-12T17:18:58.695216+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into trips**********
2019-02-12T17:18:58.706490+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into sections**********
2019-02-12T17:18:58.707319+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: moving to long term**********
2019-02-12T17:18:58.713572+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into sections**********
2019-02-12T17:18:58.719587+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: filter accuracy if needed**********
2019-02-12T17:18:58.726114+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: smoothing sections**********
2019-02-12T17:18:58.728634+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into trips**********
2019-02-12T17:18:58.735563+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: smoothing sections**********
2019-02-12T17:18:58.743777+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into sections**********
2019-02-12T17:18:58.750200+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: cleaning and resampling timeline**********
2019-02-12T17:18:58.759420+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: smoothing sections**********
2019-02-12T17:18:58.766871+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: cleaning and resampling timeline**********
2019-02-12T17:18:58.784203+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: inferring transportation mode**********
2019-02-12T17:18:58.786684+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: cleaning and resampling timeline**********
2019-02-12T17:18:58.804263+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: checking active mode trips to autocheck habits**********
2019-02-12T17:18:58.804895+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: inferring transportation mode**********
2019-02-12T17:18:58.809591+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: storing views to cache**********
2019-02-12T17:18:58.816483+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: inferring transportation mode**********
2019-02-12T17:18:58.824528+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: checking active mode trips to autocheck habits**********
2019-02-12T17:18:58.830049+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: storing views to cache**********
2019-02-12T17:18:58.835225+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: checking active mode trips to autocheck habits**********
2019-02-12T17:18:58.839861+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: storing views to cache**********
2019-02-12T17:18:58.849485+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: moving to long term**********
2019-02-12T17:18:58.860130+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: filter accuracy if needed**********
2019-02-12T17:18:58.868627+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into trips**********
2019-02-12T17:18:58.882097+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into sections**********
2019-02-12T17:18:58.898748+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: smoothing sections**********
2019-02-12T17:18:58.918229+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: cleaning and resampling timeline**********
2019-02-12T17:18:58.953223+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: inferring transportation mode**********
2019-02-12T17:18:58.975348+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: moving to long term**********
2019-02-12T17:18:58.975498+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: checking active mode trips to autocheck habits**********
2019-02-12T17:18:58.980572+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: storing views to cache**********
2019-02-12T17:18:58.983800+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: filter accuracy if needed**********
2019-02-12T17:18:58.991230+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: moving to long term**********
2019-02-12T17:18:58.994036+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into trips**********
2019-02-12T17:18:58.999841+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: filter accuracy if needed**********
2019-02-12T17:18:59.011159+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into trips**********
2019-02-12T17:18:59.011572+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into sections**********
2019-02-12T17:18:59.031005+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: segmenting into sections**********
2019-02-12T17:18:59.035495+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: smoothing sections**********
2019-02-12T17:18:59.053511+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: smoothing sections**********
2019-02-12T17:18:59.060733+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: cleaning and resampling timeline**********
2019-02-12T17:18:59.074158+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: cleaning and resampling timeline**********
2019-02-12T17:18:59.090558+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: inferring transportation mode**********
2019-02-12T17:18:59.108961+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: inferring transportation mode**********
2019-02-12T17:18:59.112706+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: checking active mode trips to autocheck habits**********
2019-02-12T17:18:59.119976+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: storing views to cache**********
2019-02-12T17:18:59.136356+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: checking active mode trips to autocheck habits**********
2019-02-12T17:18:59.142871+00:00**********UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: storing views to cache**********
`

However the views on the phone side don't update.

**Comment by jf87** [comment] 2019-02-13 13:00
Update: this seems only to be the case for my account. Other people's trips are updated.

**Comment by shankari** [comment] 2019-02-14 02:27
> Update: this seems only to be the case for my account. Other people's trips are updated.

So this is almost certainly caused by an error generated while running the pipeline. Have you checked the docs?

https://github.com/e-mission/e-mission-docs/search?p=1&q=pipeline&type=&utf8=%E2%9C%93

finds 

https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-server/troubleshooting_tips_FAQ.md#trips-on-the-phone-stay-in-draft-green-background-forever

**Comment by jf87** [comment] 2019-02-14 10:48
Thanks. I cannot see errors there. For a colleague it was the same before.
I will try and figure this out.

**Comment by shankari** [comment] 2019-02-14 18:24
Hm, if you cannot see errors there, maybe it is https://github.com/e-mission/e-mission-docs/issues/283, fixed by https://github.com/e-mission/e-mission-docs/pull/47

Although in that case, I thought it was because of the size of the survey result. But you are not actually using the survey functionality. So if that fixes the issue for you, can you send me your logs (Profile -> Email logs) so that I can see if there is anything else going on?

**Comment by shankari** [comment] 2019-04-08 18:33
@jf87 do you have any updates to this? Otherwise, can you please close the issue?

**Closed** 2019-05-13 16:04 UTC
