### ISSUE TITLE
Bug while reading data from cache

### ISSUE THREAD

**Issue by DO3B** [e-mission/e-mission-docs#417] opened 2019-06-13 09:56 UTC
Hi,  I ran into this while trying to show the "end of the trip" screen. To do that, I used the "force state" of the developer zone in order to start and end a trip. Since that, I am now unable to use the application and cannot retrieve my ancient trips. 
![Screenshot_20190613-111435](https://user-images.githubusercontent.com/17317703/59423123-628c3280-8d86-11e9-8db9-061c3bc64264.jpg)

You will find enclosed the logs. 
[loggerDB.zip](https://github.com/e-mission/e-mission-docs/files/3285327/loggerDB.zip)

**Comment by shankari** [comment] 2019-06-13 15:59
the error is from here, so it is pretty clear that `locationPoint` is undefined.

```
    var place2Geojson = function(trip, locationPoint, propertyFiller) {
      var place_gj = {
        "id": "unprocessed_"+locationPoint.data.ts,
...
```

and looking up the backtrace, it seems like `tripStartPoint` is undefined, and that is the first entry in `filteredLocationList`

```
          var tripStartPoint = filteredLocationList[0];
          var tripEndPoint = filteredLocationList[filteredLocationList.length-1];
          Logger.log("tripStartPoint = "+JSON.stringify(tripStartPoint)+"tripEndPoint = "+JSON.stringify(tripEndPoint));
          var features = [
            place2Geojson(trip, tripStartPoint, startPlacePropertyFiller),
```

But we bail early if `locationList.length` is 0. So we must have a `locationList` filled with `undefined` entries.

```
          if (locationList.length == 0) {
            return undefined;
          }
          var sortedLocationList = locationList.sort(tsEntrySort);
          var retainInRange = function(loc) {
            return (tripStartTransition.data.ts <= loc.data.ts) &&
                    (loc.data.ts <= tripEndTransition.data.ts)
          }

          var filteredLocationList = sortedLocationList.filter(retainInRange);
```

**Comment by shankari** [comment] 2019-06-13 16:06
Let's check the values that we got from local and remote. We should see these entries in the logs.

```
                Logger.log("About to dedup localResult = "+localResult.length
                    +"remoteResult = "+remoteResult.length);
                var dedupedList = combiner(localResult, remoteResult);
                Logger.log("Deduped list = "+dedupedList.length);
                resolve(dedupedList);
```

**Comment by shankari** [comment] 2019-06-13 17:00
After following the instructions to read the log on my computer
https://github.com/e-mission/e-mission-docs/blob/8095f7d240f6a643de0eec0a22b5a5a831e0d463/docs/e-mission-phone/troubleshooting_tips_faq.md#reading-the-log-on-your-computer

I see the following lines

```
202,1560415121.11,2019-06-13T01:38:41.110000-07:00,"CommunicationHelper : Result Summary
 JSON = {""phone_data"": [{""_id"": {""$oid"": ""5d01ff3be72c417879c2a297""}, ""metadata
"": {""key"": ""background/filtered_location"", ""platform"": ""android"", ""read_ts"":
0, ""time_zone"": ""America/Los_Angeles"", ""type"": ""sens length 532"
203,1560415121.117,2019-06-13T01:38:41.117000-07:00,CommunicationHelper : Got response o
rg.apache.http.message.BasicHttpResponse@deffb76 with status HTTP/1.1 200 OK
204,1560415121.1179998,2019-06-13T01:38:41.118000-07:00,js : About to dedup localResult
= 0remoteResult = 0
205,1560415121.119,2019-06-13T01:38:41.119000-07:00,js : Deduped list = 0
206,1560415121.123,2019-06-13T01:38:41.123000-07:00,js : About to dedup localResult = 0r
emoteResult = 0
207,1560415121.1239998,2019-06-13T01:38:41.124000-07:00,js : Deduped list = 0
208,1560415121.127,2019-06-13T01:38:41.127000-07:00,js : About to dedup localResult = 0remoteResult = 1
209,1560415121.129,2019-06-13T01:38:41.129000-07:00,js : Deduped list = 1
210,1560415121.131,2019-06-13T01:38:41.131000-07:00,js : tripStartPoint = undefinedtripEndPoint = undefined
```

So it looks like the server has some kind of weird entry in it?! with `""type"": ""sens length 532"`? Can you take a look at object id `5d01ff3be72c417879c2a297` in the database and see what the full entry looks like?

you can use `bson.objectid.ObjectId` to convert string -> objectid for running the query - e.g. something like

```
import emission.core.get_database as edb
import bson.objectid as boi

test_id = boi.ObjectId('5d01ff3be72c417879c2a297')
edb.get_timeseries_db().find_one({'_id': test_id})
```

If it is not in the timeseries, it will be in the usercache.

**Comment by DO3B** [comment] 2019-06-14 07:15
After yesterday night pipeline, I can now reuse my old account but no sign of `""type"": ""sens length 532"` in the database.
```
{
   '_id':ObjectId('5d01ff3be72c417879c2a297'),
   'user_id':UUID('2775ba42-1f3f-4b4c-b026-8ffe18e7c0e8'),
   'metadata':{
      'key':'background/filtered_location',
      'platform':'android',
      'read_ts':0,
      'time_zone':'America/Los_Angeles',
      'type':'sensor-data',
      'write_ts':1560411930.419,
      'write_local_dt':{
         'year':2019,
         'month':6,
         'day':13,
         'hour':0,
         'minute':45,
         'second':30,
         'weekday':3,
         'timezone':'America/Los_Angeles'
      },
      'write_fmt_time':'2019-06-13T00:45:30.419000-07:00'
   },
   'data':{
      'accuracy':20,
      'altitude':0,
      'elapsedRealtimeNanos':121425490545,
      'filter':'time',
      'fmt_time':'2019-06-13T00:45:29-07:00',
      'latitude':43.4797,
      'longitude':5.3735483,
      'sensed_speed':0,
      'ts':1560411929,
      'local_dt':{
         'year':2019,
         'month':6,
         'day':13,
         'hour':0,
         'minute':45,
         'second':29,
         'weekday':3,
         'timezone':'America/Los_Angeles'
      },
      'loc':{
         'type':'Point',
         'coordinates':[
            5.3735483,
            43.4797
         ]
      },
      'heading':0
   }
}
```

**Comment by shankari** [comment] 2019-06-14 15:22
so this is clearly due to some kind of weird entry in the database that apparently got fixed when the pipeline was run.

> So it looks like the server has some kind of weird entry in it?! with ""type"": ""sens length 532"? Can you take a look at object id 5d01ff3be72c417879c2a297 in the database and see what the full entry looks like?

This log message is from 
https://github.com/e-mission/cordova-server-communication/blob/99ca9ed362fa5bc0f5b402babb3fc06fcc2b5762/src/android/CommunicationHelper.java#L109

and it looks like we just print the first 200 characters and then the total length
So that explains the `""type"": ""sens length 532"`, it was `type: sensor-data...` truncated at 'sens' and the complete length was 532.

But unfortunately, we don't have a record of what the rest of the entry was, and it is now fixed on the server as well.

I'm going to leave this open in case you can reproduce again while testing. If you can, please check the entry in the usercache (before the pipeline is run) ASAP.

**Comment by shankari** [comment] 2019-07-09 18:54
This was reproduced by @PatGendre in #413. Looking at the newly added logs, I see


We find transitions that define a single trip

```
423,1562597394.394,2019-07-08T07:49:54.394000-07:00,"js : Unprocessed trip starting at {""_id"":{""$oid"":""5d230acf2d651da6fa4e64fe""},""metadata"":{""key"":""statemachine/transition"",""platform"":""android"",""read_ts"":0,""time_zone"":""Europe/Brussels"",""type"":""message"",""write_ts"":1562575535.212},""user_id"":{""$uuid"":""bd8aeff5ec6643b08962cef1ca23b86b""},""data"":{""currState"":""local.state.waiting_for_trip_start"",""transition"":""local.transition.exited_geofence"",""ts"":1562575535.199}}
ends at {""_id"":{""$oid"":""5d230acf2d651da6fa4e6520""},""metadata"":{""key"":""statemachine/transition"",""platform"":""android"",""read_ts"":0,""time_zone"":""Europe/Brussels"",""type"":""message"",""write_ts"":1562577613.682},""user_id"":{""$uuid"":""bd8aeff5ec6643b08962cef1ca23b86b""},""data"":{""curr_state"":""local.state.ongoing_trip"",""transition"":""local.transition.stopped_moving"",""ts"":1562577613}}"
424,1562597394.41,2019-07-08T07:49:54.410000-07:00,"js : No further unprocessed trips started, exiting loop"
425,1562597394.425,2019-07-08T07:49:54.425000-07:00,js : Mapped into1 trips. yay!
```

The transitions are:
- start:
    - ts: 1562575535.199 (2019-07-08T10:45:35.199000+02:00)
    - write_ts: 1562575535.212 (2019-07-08T10:45:35.212000+02:00)
- end:
    - ts: 1562577613 (2019-07-08T11:20:13+02:00)
    - write_ts: 1562577613.682 (2019-07-08T11:20:13.682000+02:00)

We try to retrieve the locations in that range 

```
426,1562597394.4520001,2019-07-08T07:49:54.452000-07:00,js : About to pull location data for range Mon Jul 08 2019 10:45:35 GMT+0200 -> Mon Jul 08 2019 11:20:13 GMT+0200
...
429,1562597395.4770002,2019-07-08T07:49:55.477000-07:00,CommunicationHelper : Got response org.apache.http.message.BasicHttpResponse@ee6d4fa with status HTTP/1.1 200 OK
430,1562597395.495,2019-07-08T07:49:55.495000-07:00,"CommunicationHelper : Result Summary JSON = {""phone_data"": [{""_id"": {""$oid"": ""5d230acf2d651da6fa4e6506""}, ""metadata"": {""key"": ""background/filtered_location"", ""platform"": ""android"", ""read_ts"": 0, ""time_zone"": ""Europe/Brussels"", ""type"": ""sensor-d length 556"
431,1562597395.516,2019-07-08T07:49:55.516000-07:00,js : About to dedup localResult = 0remoteResult = 1
432,1562597395.524,2019-07-08T07:49:55.524000-07:00,js : Deduped list = 1
```

but there's only one? That seems surprising since we generally only end the trip if we have multiple points within a 100m radius.

```
433,1562597395.534,2019-07-08T07:49:55.534000-07:00,js : tripStartPoint = undefinedtripEndPoint = undefined
434,1562597395.5410001,2019-07-08T07:49:55.541000-07:00,"js : BUG 417 check: locationList = [{""_id"":{""$oid"":""5d230acf2d651da6fa4e6506""},""metadata"":{""key"":""background/filtered_location"",""platform"":""android"",""read_ts"":0,""time_zone"":""Europe/Brussels"",""type"":""sensor-data"",""write_ts"":1562575537.226},""user_id"":{""$uuid"":""bd8aeff5ec6643b08962cef1ca23b86b""},""data"":{""accuracy"":13.82,""altitude"":181.10000610351562,""bearing"":0,""elapsedRealtimeNanos"":3263168000000,""filter"":""time"",""fmt_time"":""8 juil. 2019 10:45:26 AM"",""latitude"":43.4797145,""longitude"":5.3732738,""sensed_speed"":0,""ts"":1562575526.239}}]"
```

And that one point has
- ts: 1562575526.239 (2019-07-08T10:45:26.239000+02:00)
- write_ts: 1562575537.226 (2019-07-08T10:45:37.226000+02:00)

Aha! so the point has a pretty mismatched `ts` and `write_ts`. This causes the `write_ts` to be within the query range, but the `ts` to be before the first transition. So when we filter the `data.ts` for the range, we get an empty array and the start and end points are defined.

```
          if (locationList.length == 0) {
            return undefined;
          }
          var sortedLocationList = locationList.sort(tsEntrySort);
          var retainInRange = function(loc) {
            return (tripStartTransition.data.ts <= loc.data.ts) &&
                    (loc.data.ts <= tripEndTransition.data.ts)
          }

          var filteredLocationList = sortedLocationList.filter(retainInRange);
          var tripStartPoint = filteredLocationList[0];
          var tripEndPoint = filteredLocationList[filteredLocationList.length-1];
```

The naive fix is to do a second check for length and return undefined in that case as well.

However, I am a bit surprised that we got only one location before the trip end. @PatGendre, were you manually triggering the trip start/end? Otherwise we expect to have a bunch of closely grouped points before we detect the trip end.

**Comment by shankari** [comment] 2019-07-09 19:01
> However, I am a bit surprised that we got only one location before the trip end. @PatGendre, were you manually triggering the trip start/end? Otherwise we expect to have a bunch of closely grouped points before we detect the trip end.

Alas, we don't have any logs for the time that the trip was started and ended (Mon Jul 08 2019 10:45:35 GMT+0200 -> Mon Jul 08 2019 11:20:13 GMT+0200) because of the reinstall. So I am not sure how we end up with this situation unless the user is manually generating FSM transitions for testing.

**Comment by shankari** [comment] 2019-07-09 19:08
Potential 3 line fix added to PR https://github.com/e-mission/e-mission-phone/pull/596
@DO3B @PatGendre if you test that in your app, then I can merge both fixes at the same time.

**Comment by PatGendre** [comment] 2019-07-10 06:48
@shankari thank you, I didn't force end or start trip. 
As you said, we are frequently reinstalling the app so some log data is lost...
As the error was the same as @DO3B , I thought this was also due to the same cause, ""type"": ""sens length 532"" so presumably clicking to the "check sensed data" button in the profile screen?

We can test the app with the 3 line fix tomorrow : and testing would mean click on the "check sensed data" button to see if something gets wrong...

**Comment by shankari** [comment] 2019-07-10 12:57
The `""type"": ""sens length 532""` was a false alarm, caused because we truncate the displayed result when we log it from the communication helper (https://github.com/e-mission/e-mission-docs/issues/417#issuecomment-502151233)

> and it looks like we just print the first 200 characters and then the total length
So that explains the ""type"": ""sens length 532", it was type: sensor-data... truncated at 'sens' and the complete length was 532.

> clicking to the "check sensed data" button

I really don't think this is related to "check sensed data". When @DO3B originally reported this, he was testing with forcing state which makes a lot more sense.

> I used the "force state" of the developer zone in order to start and end a trip

 Did you use "End trip and Force Sync" maybe? That functionality also forces the state change.

**Comment by PatGendre** [comment] 2019-07-10 15:28
Thanks, I don't think I ended trip either. 
We'll test tomorrow and I tell you.

**Comment by PatGendre** [comment] 2019-07-15 13:23
Hi @shankari , we did not the problem again, so I think you can close.

**Closed** 2019-07-15 19:01 UTC
Labels: bug
