### ISSUE TITLE
Irrelevant error message when adding trip details - app version 1.2.2

### ISSUE THREAD

**Issue by MaliheTabasi** [e-mission/e-mission-docs#881] opened 2023-04-09 02:03 UTC
@shankari  
When I try to add trip details, at the last step, I got the error message that can be seen in the screenshot below, which is not relevant as there are no start and end time in the trip details survey.

![photo1681005751](https://user-images.githubusercontent.com/49550315/230750474-18fc1c58-07d2-4810-a0d6-ad157ce2a37d.jpeg)

**Comment by shankari** [comment] 2023-04-10 02:39
Duplicate of #879. Fixed, will be included in next release.

**Closed by shankari** 2023-04-10 02:39 UTC

**Comment by MaliheTabasi** [comment] 2023-04-13 01:03
@shankari  Can I pls know when is the next release?

**Comment by shankari** [comment] 2023-04-13 01:32
@MaliheTabasi if you have been following the issues on GitHub, you will see that there were two P0 issues in RC1.
This was an easy fix - the other one required a fairly significant rewrite of the composite trip code and is just getting done (#880). Once that other issue is closed, I will push out the next release.

Note that while working on that issue, I came up with several questions around the matching.
https://github.com/e-mission/e-mission-docs/issues/880#issuecomment-1502750747

I will file a separate issue for these questions but I think we might want to have a meeting (maybe tomorrow assuming I get the release done tonight) to discuss them.

**Comment by MaliheTabasi** [comment] 2023-04-13 01:39
> 

@shankari  Thank you. Sure.
