### ISSUE TITLE
Installing emTripLog on a OnePlus phone?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#471] opened 2019-11-22 15:15 UTC
We have a user in France with a One Plus 6 phone
and she could not install emtriplog from the https://tripaware.damajash.org/ instructions.
See attached screenshot.
![tripaware-install](https://user-images.githubusercontent.com/5039447/69437164-0d941580-0d43-11ea-8052-794a45946c66.jpg)

**Comment by shankari** [comment] 2019-11-22 15:23
Is this persistent? Could it just be a connection issue? Because it does say "Essayez a nouveau". 
Also, when the user clicks on "envoyer des commentaires", what additional information do they get?

**Comment by shankari** [comment] 2019-11-22 15:26
@deepalics0044 I think you said that you had a One Plus. Can you try to install emTripLog again and see whether you encounter any issues?

**Comment by PatGendre** [comment] 2019-11-22 15:56
@shankari the user tested again after emptying the play store cache and restarting.
She tried to send the comments, which sent a screen capture and a log to the developer (you I suppose).
And she could not save the logs.

**Comment by shankari** [comment] 2019-11-22 20:09
@PatGendre I don't see any reports in the play store console from a One Plus. There were apparently a couple of reports from a Moto G which I should look into. I will see whether they show up later - there may be a lag in terms of posting to the console.

**Comment by deepalics0044** [comment] 2019-11-22 20:10
I'll look into it. Give me some time.

**Comment by shankari** [comment] 2019-11-22 21:54
Thanks @deepalics0044 
Just to clarify, the task is very simple.
You just need to install emTripLog (https://play.google.com/store/apps/details?id=edu.berkeley.eecs.embase) from the play store and see if it works :)

**Comment by shankari** [comment] 2019-11-23 02:57
@hariv I think you have a OnePlus too, can you please try to install https://play.google.com/store/apps/details?id=edu.berkeley.eecs.embase as well and see if it works :)

**Comment by PatGendre** [comment] 2019-11-23 06:56
@shankari thanks for having asked other users:-) Yes there may be a delay for the report log to be sent...

**Comment by shankari** [comment] 2019-11-23 22:25
@hariv responded offline and said that he no longer has a One Plus.
@PatGendre I still don't see anything in the play console. Do other e-mission apps install - e.g. the base e-mission app or the FabMob app?

**Comment by hariv** [comment] 2019-11-24 02:36
@anmol0591 has a OnePlus phone and has volunteered to try.

**Comment by hariv** [comment] 2019-11-24 06:22
@shr22avan was able to install it on his OnePlus 6.  It asked him for a QR code, and on scanning the QR code showed him screens informing him of what is collected, his rights and asking for his consent. I have attached screenshots of what he saw:

![WhatsApp Image 2019-11-23 at 20 04 51](https://user-images.githubusercontent.com/1237899/69490614-a7d98380-0e3f-11ea-992d-f9ea7c0c94a2.jpeg)
![WhatsApp Image 2019-11-23 at 20 04 51 (1)](https://user-images.githubusercontent.com/1237899/69490615-ac9e3780-0e3f-11ea-9908-3dfba006e8a9.jpeg)
![WhatsApp Image 2019-11-23 at 20 04 51 (2)](https://user-images.githubusercontent.com/1237899/69490618-b031be80-0e3f-11ea-8233-67c82b2bd7b8.jpeg)
![WhatsApp Image 2019-11-23 at 20 04 51 (3)](https://user-images.githubusercontent.com/1237899/69490619-b2941880-0e3f-11ea-98bc-624448f79724.jpeg)
![WhatsApp Image 2019-11-23 at 20 04 51 (4)](https://user-images.githubusercontent.com/1237899/69490620-b4f67280-0e3f-11ea-9205-13e6f9b7cda7.jpeg)

**Comment by PatGendre** [comment] 2019-11-24 07:18
@hariv @shr22avan thanks a lo for the detailed screenshots! So basically the install works, I have exactly the same on my huawei.
@shankari yes the user had already the fabmob e-mission app installed.

**Comment by shankari** [comment] 2019-11-24 15:32
@shr22avan thank you so much for checking! It was particularly nice to include screenshots so that we can confirm for sure that it worked.

@PatGendre it seems like there is nothing fundamentally incompatible with the OnePlus 6.
I also don't see any reports on the Google Play console.

Does the fabmob fork still have the ionic deploy code in it? Because if so, the user could just click the link in the second step, or scan the QR code, and it would put the TripAware UI into the fabmob app.

Alternatively, can the user try installing the emission (not emTripLog) app and then clicking on the link. e-mission does have the ionic deploy code in it so it will also work.
https://play.google.com/store/apps/details?id=edu.berkeley.eecs.emission

**Comment by PatGendre** [comment] 2019-11-25 07:15
@shankari thanks! I have asked the user to try the alternative e-mission install.
I don't think we could do that with our fabmob app (I'll ask Yann to check).

**Comment by PatGendre** [comment] 2019-11-25 07:50
@shankari it worked :-) She saw the nice polar bear.
So I could the issue? (even if we don't know why installing directly from embase did not).

**Comment by PatGendre** [comment] 2019-11-25 09:09
@shankari I asked Yann, he did not remove the Ionic deploy code, so I tested to click on the emission link and open the fabmob app, it proposed me to change UI, however the UI download did not terminate, so clicked on the OK button, and the tripaware UI had been installed, however I was proposed to log in via gmail and I could not, I had a 500 http error. Maybe we have changed some other things in our code that make the install not possible?    
Anyway it was a good idea to ask the user to do the tripaware install via the original Berkeley instead of via our fabmob fork;-)

**Comment by shankari** [comment] 2019-11-25 17:59
> and when proposed to log in via gmail and I had a 500 http error.
Maybe because we have changed some other things in our code that make the install not possible?

Ah yes, I think that the fabmob fork is using OpenIdConnect auth, so you don't have a google client id. So you can't log in to the tripaware server which expects a matching google client ID.

**Comment by PatGendre** [comment] 2019-11-25 18:06
Ok, thanks, yes use openid, not Google auth.

**Comment by shankari** [comment] 2019-11-25 18:10
> even if we don't know why installing directly from embase did not

I would really like to understand why installing from embase did not work, if the user can be patient enough to do some more testing. I am pretty sure I picked the same settings in the play store for both emission and embase, so there should not be any difference between the two.

One difference is that I updated emTripLog after the migration to API 26 (on March 27, 2019) but I did not update emission (last update is from October 19, 2018). But the FabMob app does have the API 26 changes and it worked. And of course, the existing emTripLog worked for the Indian user.

So I can't think of a reason why emTripLog should not work. So after the user has finished testing with the polar bears, it would be interesting to have them try to reinstall emTripLog and if it consistently fails, manually generate a bug report and email it to me.

I am happy to provide additional instructions when the user is ready to do this.

**Comment by shankari** [comment] 2019-11-26 16:27
Error reported by the user

![Screenshot_20191126-111746](https://user-images.githubusercontent.com/2423263/69652485-930b1480-1026-11ea-9074-4a41156b1231.jpg)

**Comment by shankari** [comment] 2019-11-26 16:55
Aha! As per 
https://www.androidpit.com/how-to-solve-google-play-store-errors
it looks like error 505 is related to having two or more apps with duplicate permissions.

In this case, this is presumably the FabMob app and the emTripLog app. This also explains:
- why the emission app was installed, since has not been updated after the API 26 changes so it has a different set of permissions
- why the install worked for @shr22avan - he did not have the FabMob app installed

I was not aware of this restriction on apps in the store, and it does not appear to be enforced on all phones. For example @PatGendre is able to install both emTripLog and the FabMob app in parallel on his Huawei phone.

**Comment by shankari** [comment] 2019-11-26 16:57
hm, apparently this is a "new security feature" that is undocumented, or at least not very clearly documented.
https://stackoverflow.com/questions/27043933/install-failed-duplicate-permission-c2d-message

**Comment by shankari** [comment] 2019-11-26 17:07
@PatGendre it seems like we need to make more changes to allow two apps from the same platform to be installed on the same device, at least for strict devices.

I am not sure which permission they are complaining about, though. It looks like the system log file will list the actual permission, but it has not been uploaded to the play console, and 
https://duckduckgo.com/?q=where+can+I+see+installation+errors+in+google+play+console&t=ffsb&ia=web doesn't return anything.

**Comment by shankari** [comment] 2019-11-26 17:14
@PatGendre I am not sure how much more patience the user will have, so I am listing multiple alternatives here.

- for the short-term, they can either:
   - uninstall FabMob app + install emTripLog OR
   - continue using the e-mission app, but manually enable location permissions in the app settings. Because the e-mission app has not been updated after API 26, it does not prompt for permissions.
- for the long-term, can they send me the system logs?
   - enable developer options (lots of guides: https://duckduckgo.com/?q=enable+developer+options+android&t=ffsb&ia=web)
   - reproduce the failed install (e.g. with FabMob app installed, try to install emTripLog, or with emTripLog installed, try to install FabMob)
   - go to the developer options
   - click on "Take bug report"
   - email me the result

I will also send this to the user directly and thank them again for all their patience.

**Comment by PatGendre** [comment] 2019-11-26 17:28
@shankari thanks a lot, this is a tricky issue...
I will also tell her that this is a subtle cohabitation between the 2 apps but maybe she will do the second test, as she is very reactive!

**Comment by shankari** [comment] 2019-11-27 06:10
The user reported that on retrying, she was able to install both emTripLog and the FabMob app. This was true when either app was installed first - e.g. emTripLog first and then FabMob second, or vice versa.

She also sent me logs, but they only cover the range from `11-26 18:29:58` to `11-26 19:07:19` so don't include the installation failures.

**Comment by shankari** [comment] 2019-12-02 17:33
@PatGendre if I read the users' email correctly, she was able to install both emTripLog and the FabMob app when she retried. So it looks like the first failure was something intermittent and there is no real bug here.

I am closing this as not a bug - please LMK if we need to look at this any more.

**Closed** 2019-12-02 17:33 UTC
Labels: not-a-bug
