### ISSUE TITLE
Null/NaN values for ON_FOOT from aggregate call to server

### ISSUE THREAD

**Issue by tms-martins** [e-mission/e-mission-docs#422] opened 2019-06-25 09:28 UTC
Using 
- app: master
- server: ground_truth_matching
- however, in this app branch aggregate calls go to the e-mission server.

In metrics.js, `$scope.fillFootprintAggVals`, I noticed that the [`aggrCarbonData` returned from `getAvgSummaryDataRaw()`](https://github.com/e-mission/e-mission-phone/blob/f03c1fff43933141c33eb1723e501f871ffaad94/www/js/metrics.js#L761) contained a NaN value for ON_FOOT, e.g.
```
[
  {
    "key": "ON_FOOT",
    "values": null
  },
  {
    "key": "CAR",
    "values": 944804
  },
  {
    "key": "AIR_OR_HSR",
    "values": 39832
  },
  {
    "key": "BICYCLING",
    "values": 145767
  }
]
```

So I dug down to `getAvgSummaryDataRaw` and looked at [the `data` array returned by `getAvgDataFromMetrics()`](https://github.com/e-mission/e-mission-phone/blob/f03c1fff43933141c33eb1723e501f871ffaad94/www/js/metrics.js#L897). The `data` array contains *triplets* (the third of which is a date). Whenever the key is `ON_FOOT`, the second value is `null` (when *stringify-ed*). e.g.
```
{
  "key": "ON_FOOT",
  "values": [
    [
      1469318400,
      null,
      "2016-07-24T00:00:00+00:00"
    ],
  ...
}
```
Not sure if this is a side effect of using the ground_truth_matching server, but since the aggregate calls are made to the official e-mission server, that shouldn't be the case.

**Comment by shankari** [comment] 2019-06-29 02:28
@tms-martins does this happen for all data ranges?

**Comment by shankari** [comment] 2019-06-29 05:53
@tms-martins I am not able to reproduce with the standard call; when I use the refresh button with no edits, and add a breakpoint at https://github.com/e-mission/e-mission-phone/blob/master/www/js/metrics.js#L499
I get blank aggregate metrics. Note from the closure variables that I am in fact connecting to the e-mission server.

<img width="848" alt="Screen Shot 2019-06-28 at 10 49 31 PM" src="https://user-images.githubusercontent.com/2423263/60380263-6dd29580-99f7-11e9-87a1-d2ce4fce25ff.png">

Did you follow any additional steps to get non-blank data?

**Comment by shankari** [comment] 2019-06-29 05:58
FYI, the parameters for the query were  as shown in the screenshot below. Would be great to get the parameters for your query so that I can try to reproduce.

<img width="1440" alt="Screen Shot 2019-06-28 at 10 56 28 PM" src="https://user-images.githubusercontent.com/2423263/60380286-17b22200-99f8-11e9-80c2-a5711b0a2572.png">

or to make it easier to copy/paste...

```
{freq: "D", start_time: 1560556800, end_time: 1561680000, metric_list: ["duration", "median_speed", "count", "distance"], is_return_aggregate: true}
```

**Comment by tms-martins** [comment] 2019-07-01 10:58
I should have stated the date range. Typically from June 16 2015 to the present, as in:
```
{"freq":"D","start_time":1434319200,"end_time":1561978117,"metric":""}
```
(if I don't set a range, it runs with the present date by default and does return blank aggregate metrics)

I can post `results.data.aggregate_metrics` here if you like. The first item is
```
  [
    {
      "ts": 1437523200,
      "local_dt": {
        "year": 2015,
        "month": 7,
        "day": 22,
        "hour": 0,
        "minute": 0,
        "second": 0,
        "weekday": 2,
        "timezone": "UTC"
      },
      "fmt_time": "2015-07-22T00:00:00+00:00",
      "nUsers": 1,
      "WALKING": 3806.900153875351,
      "BICYCLING": 3276.1340384483337,
      "TRAIN": 2541.43399977684,
      "CAR": 1088.776636838913
    }
  ],
```
First thing I can see is that it uses WALKING instead of ON_FOOT, as do the other 3 items; maybe related?

**Comment by shankari** [comment] 2019-07-01 22:36
ok, I can reproduce this now; taking a look.

**Comment by shankari** [comment] 2019-07-01 22:45
You are right that values is an array of arrays; each of the sub arrays has 3 elements and the second one is consistently `NaN` for the case of `ON_FOOT` - e.g.

```
Array (15) = $1
0 [1469318400, NaN, "2016-07-24T00:00:00+00:00"] (3)
1 [1469491200, NaN, "2016-07-26T00:00:00+00:00"] (3)
2 [1473984000, NaN, "2016-09-16T00:00:00+00:00"] (3)
3 [1474070400, NaN, "2016-09-17T00:00:00+00:00"] (3)
4 [1474934400, NaN, "2016-09-27T00:00:00+00:00"] (3)
5 [1475020800, NaN, "2016-09-28T00:00:00+00:00"] (3)
6 [1475107200, NaN, "2016-09-29T00:00:00+00:00"] (3)
7 [1475452800, NaN, "2016-10-03T00:00:00+00:00"] (3)
8 [1475625600, NaN, "2016-10-05T00:00:00+00:00"] (3)
9 [1475712000, NaN, "2016-10-06T00:00:00+00:00"] (3)
10 [1476662400, NaN, "2016-10-17T00:00:00+00:00"] (3)
11 [1477440000, NaN, "2016-10-26T00:00:00+00:00"] (3)
12 [1477526400, NaN, "2016-10-27T00:00:00+00:00"] (3)
13 [1477872000, NaN, "2016-10-31T00:00:00+00:00"] (3)
14 [1477958400, NaN, "2016-11-01T00:00:00+00:00"] (3)
```

I believe that the second value is supposed to represent the metric number (e.g. for the `DISTANCE` metric, that would be the `ON_FOOT` distance for that day).

I also note that the value that we get from the server (`results.data.aggregate_metrics` from `getAggMetricsFromServer().then(function(results) {`) has `WALKING` and no `ON_FOOT`. So this must be an issue with the conversion between the two points.

```
Array (373) = $2
0 Object

CAR: 3048.566673517227
WALKING: 7627.244616985321
fmt_time: "2016-07-24T00:00:00+00:00"
local_dt: {year: 2016, month: 7, day: 24, hour: 0, minute: 0, …}
...
```

**Comment by shankari** [comment] 2019-07-01 23:36
ok, so the bug is in 

```
                if (field == field.toUpperCase()) {
                    if (field === "WALKING" || field === "RUNNING") {
                      field = "ON_FOOT";
                    }
                    if (field in mode_bins == false) {
                        mode_bins[field] = []
                    }
                    mode_bins[field].push([metric.ts, Math.round(metric[field] / metric.nUsers), metric.fmt_time]);
                }
```

Concretely, if the field is `WALKING` or `RUNNING` we set the `field = ON_FOOT`. But then we try to calculate the metric by accessing `metric[field]`. Since we haven't yet changed the metric array, metric['ON_FOOT'] doesn't exist and so we get a `NaN`

**Comment by shankari** [comment] 2019-07-01 23:55
This was added in https://github.com/e-mission/e-mission-phone/commit/353916b4355b60c99f657e766da7bc985e6bd291, part of https://github.com/e-mission/e-mission-phone/pull/88

I am not sure how this ever worked, although I see a screenshot showing valid values in the original PR
https://github.com/e-mission/e-mission-phone/pull/88#issuecomment-235176129

**Comment by shankari** [comment] 2019-07-01 23:57
so the naive fix would be something like 

```
                if (field == field.toUpperCase()) {
                    if (field === "WALKING" || field === "RUNNING") {
                      // ensure that there is an entry for ON_FOOT, see
                      // https://github.com/e-mission/e-mission-docs/issues/422
                      metric["ON_FOOT"] = metric[field];
                      field = "ON_FOOT";
                    }
                    if (field in mode_bins == false) {
                        mode_bins[field] = []
                    }
                    mode_bins[field].push([metric.ts, Math.round(metric[field] / metric.nUsers), metric.fmt_time]);
                }
```

but that won't handle the case in which we have BOTH `WALKING` and `RUNNING` entries at the same time.

**Comment by shankari** [comment] 2019-07-02 00:19
implemented a slightly more complicated fix in which we maintain a running counter of the values.

**Comment by shankari** [comment] 2019-07-02 00:27
There is similar code in `getDataFromMetrics` and while trying to fix that, I see that this has already been fixed in https://github.com/e-mission/e-mission-phone/commit/7f38a53786f462e473bb0adb560570c50cacb286

Unfortunately, that only fixed that one location, *and* fixed it naively, assuming that only one of `WALKING` or `RUNNING` would show up.

**Closed** 2019-07-02 13:41 UTC
