### ISSUE TITLE
server setup script: "ResolvePackageNotFound"  for 4 python packages 

### ISSUE THREAD

**Issue by lefterav** [e-mission/e-mission-docs#516] opened 2020-03-30 23:28 UTC
I tried to install the server of the `gis-based-mode-detection` branch. I run the following script:
`bash setup/setup.sh` 

and it gave me the following error
```

ResolvePackageNotFound: 
scikit-learn==0.18.1=np112py36_1
scipy==0.19.0=np112py36_0
numpy==1.12.1=py36_0
requests==2.14.2=py36_0

```

**Comment by shankari** [comment] 2020-03-31 00:58
Duplicate of https://github.com/e-mission/e-mission-docs/issues/502

> I created a "dev" docker environment which embeds the correct conda version and works. Using that environment, or manually installing version `4.5.12` of miniconda should work.

**Closed** 2020-03-31 00:59 UTC
