### ISSUE TITLE
Sensitivity of travel range/time stopped?

### ISSUE THREAD

**Issue by JackBikes** [e-mission/e-mission-docs#562] opened 2020-08-14 18:44 UTC
As I've left my house to walk my dog, I will get notifications when I pause for just one or two seconds to wait for him asking me "How did you get here?" is it possible to reduce this sensitivity to increase the chances that a trip has actually ended? If a bicyclist is stopped at a light, I don't want that to signal the end of a trip.

**Comment by shankari** [comment] 2020-08-14 21:05
This is a duplicate of #372.
@JackBikes can you please email me your logs? (Profile -> Email Log).
I tried to get some consensus on how to tweak this back when #372 was reported but didn't get the logs to proceed.

@asiripanich maybe this time we will get it right!

**Closed** 2020-08-14 21:05 UTC

**Comment by JackBikes** [comment] 2020-08-14 21:08
Just sent to your Berkeley email address.

Jack Todd
Director of Communications and Policy, Bicycle Colorado
Pronouns: he/him/his
1525 Market Street, Suite 100
Denver, CO 80202
Cell: (303) 523-4231
bicyclecolorado.org

<https://www.bicyclecolorado.org/bike-news/social-justice/>
