### ISSUE TITLE
Error 6 in location settings

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-docs#528] opened 2020-04-28 10:16 UTC
One of our user reported that they cannot sync data to server.

I had a look in the server log and found **Token expired** alternate with **Invalid token** many times.

I am not certain if this is related to what user reported.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emission/net/api/cfc_webapp.py", line 447, in getUUID
    retUUID = enaa.getUUID(request, auth_method, inHeader)
  File "/usr/src/app/emission/net/auth/auth.py", line 63, in getUUID
    retUUID = getUUIDFromToken(authMethod, userToken)
  File "/usr/src/app/emission/net/auth/auth.py", line 37, in getUUIDFromToken
    userEmail = AuthMethodFactory.getAuthMethod(authMethod).verifyUserToken(token)
  File "/usr/src/app/emission/net/auth/google_auth.py", line 67, in verifyUserToken
    verifiedEmail = self.__verifyTokenFields(tokenFields, "audience", "issuer")
  File "/usr/src/app/emission/net/auth/google_auth.py", line 34, in __verifyTokenFields
    (tokenFields, audienceKey))
ValueError: Invalid token {'error': 'invalid_token', 'error_description': 'Invalid Value'}, does not contain audience
Traceback (most recent call last):
  File "/usr/src/app/emission/net/auth/google_auth.py", line 55, in verifyUserToken
    tokenFields = goi.verify_oauth2_token(token, gatr.Request())
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/google/oauth2/id_token.py", line 97, in verify_oauth2_token
    certs_url=_GOOGLE_OAUTH2_CERTS_URL)
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/google/oauth2/id_token.py", line 78, in verify_token
    return jwt.decode(id_token, certs=certs, audience=audience)
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/google/auth/jwt.py", line 239, in decode
    _verify_iat_and_exp(payload)
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/google/auth/jwt.py", line 189, in _verify_iat_and_exp
    raise ValueError('Token expired, {} < {}'.format(latest, now))
ValueError: Token expired, 1588062458 < 1588062584
```

**Comment by atton16** [comment] 2020-04-28 10:17
@asiripanich

**Comment by shankari** [comment] 2020-04-28 14:39
I vaguely remember seeing this kind of error in the past but it related to an invalid client ID and I added in some fixes back in 2016.
(https://github.com/e-mission/cordova-jwt-auth/issues/8)

Some background:
For greater security, our google auth login generates token that are valid for an hour at a time. The token has to be renewed when it expires.

This limits the window of possible malicious access using our key - if the key is compromised and we change it, then token renewal will be turned off.

For some reason, this user is continuously generating tokens that are expired by the time our server gets them.

Can you:
- ask the user to check whether their date/time is synced automatically and is current?
- ask the user to send the client logs? I added a bunch of logging as part of https://github.com/e-mission/cordova-jwt-auth/issues/8 so if it is a client issue I can debug it pretty quickly

**Comment by asiripanich** [comment] 2020-04-28 14:44
I will take care of 
- ask the user to check whether their date/time is synced automatically and is current?
- ask the user to send the client logs?

@atton16 Could you check that the server date/time is synced automatically and is current?

**Comment by asiripanich** [comment] 2020-04-29 00:57
@shankari i have just sent the reported user’s log file to your email.

**Comment by shankari** [comment] 2020-04-29 01:31
I am not sure that the token expiration is the root cause of the problem. Do you have any further information about what the user means when they say that they cannot sync to the server? 

I see no errors and multiple successful syncs to the server. There is just no data to push because no trips have been recorded yet.

First sync, skipped

```
13,1588040511.32,2020-04-27T19:21:51.320000-07:00,"ServerSyncAdapter : intro is not yet done, skip sync by exiting immediately..."
```

Second sync, nothing to push

```
484,1588046625.78,2020-04-27T21:03:45.780000-07:00,ServerSyncAdapter : Starting sync with push
493,1588046625.816,2020-04-27T21:03:45.816000-07:00,"BuiltinUserCache : We don't have a completed trip, so we don't want to push anything yet"
495,1588046625.83,2020-04-27T21:03:45.830000-07:00,"ServerSyncAdapter : Push complete, now pulling"
500,1588046626.3739998,2020-04-27T21:03:46.374000-07:00,CommunicationHelper : Got response org.apache.http.message.BasicHttpResponse@40238a4 with status HTTP/1.1 200 OK
501,1588046626.394,2020-04-27T21:03:46.394000-07:00,"CommunicationHelper : Result Summary JSON = {""server_to_phone"": []}
 length 24"
```

Third sync, nothing to push

```
681,1588058558.369,2020-04-28T00:22:38.369000-07:00,ServerSyncAdapter : Starting sync with push
693,1588058558.411,2020-04-28T00:22:38.411000-07:00,"BuiltinUserCache : We don't have a completed trip, so we don't want to push anything yet"
700,1588058559.189,2020-04-28T00:22:39.189000-07:00,CommunicationHelper : Got response org.apache.http.message.BasicHttpResponse@40238a4 with status HTTP/1.1 200 OK
701,1588058559.2120001,2020-04-28T00:22:39.212000-07:00,"CommunicationHelper : Result Summary JSON = {""server_to_phone"": []}
 length 24"
```

Fourth sync, nothing to push

```
1051,1588065948.843,2020-04-28T02:25:48.843000-07:00,ServerSyncAdapter : Starting sync with push
1063,1588065948.887,2020-04-28T02:25:48.887000-07:00,"BuiltinUserCache : We don't have a completed trip, so we don't want to push anything yet"
1065,1588065948.9020002,2020-04-28T02:25:48.902000-07:00,"ServerSyncAdapter : Push complete, now pulling"
1109,1588065950.0839999,2020-04-28T02:25:50.084000-07:00,CommunicationHelper : Got response org.apache.http.message.BasicHttpResponse@68a045b with status HTTP/1.1 200 OK
1110,1588065950.093,2020-04-28T02:25:50.093000-07:00,"CommunicationHelper : Result Summary JSON = {""server_to_phone"": []}
 length 24"
```

**Comment by asiripanich** [comment] 2020-04-29 01:37
So the user reported that he made some trips yesterday but none of that showed up on emTripLog. The user also assured that the location permission was configured to “always allow” and the app has been running on the background.

**Comment by shankari** [comment] 2020-04-29 01:44
First, the user is on android, so there is no "always allow" option.

Second, if the tracking was correct but the sync was broken, the trips would show up in emTripLog as draft. If the trips are not showing up at all, the sync is not broken, the tracking is not working.

Finally, I do see several errors around location settings in the log. There should be a notification in the notification bar indicating that there are tracking errors.

```

605,1588058557.621,2020-04-28T00:22:37.621000-07:00,"NotificationHelper : Generating notify with id 87225377, message Error 6 in location settings and pending intent PendingIntent{161ca5c: android.os.BinderProxy@1736165}"
656,1588058558.024,2020-04-28T00:22:38.024000-07:00,"NotificationHelper : Generating notify with id 87225377, message Error 6 in location settings and pending intent PendingIntent{6f0239: android.os.BinderProxy@307807e}"
139,1588040571.0279999,2020-04-27T19:22:51.028000-07:00,"NotificationHelper : Generating notify with id 87225377, message Error 6 in location settings and pending intent PendingIntent{ae39a78: android.os.BinderProxy@cc98551}"
```

**Comment by asiripanich** [comment] 2020-04-29 01:50
I meant to say the android equivalent of “always allow”. 😅

Umm, let me check again. By the way, can we tell from the log if the user has the correct location permission for emTripLog?

**Comment by shankari** [comment] 2020-04-29 02:19
The permissions seem to be fine, looks like the settings are wrong. Does the user allow fused location in the settings?

```
132,1588040570.8760002,2020-04-27T19:22:50.876000-07:00,TripDiaryStateMachineService : Checking location settings and permissions for request Request[PRIORITY_HIGH_ACCURACY requested=30000ms fastest=5000ms]
133,1588040570.879,2020-04-27T19:22:50.879000-07:00,TripDiaryStateMachineService : checkSelfPermission returned 0
134,1588040570.8820002,2020-04-27T19:22:50.882000-07:00,"TripDiaryStateMachineService : checkPermissions returned true, checking settings"
135,1588040570.894,2020-04-27T19:22:50.894000-07:00,TripDiaryStateMachineService : Got back result com.google.android.gms.internal.zzcdu@aa760ea
136,1588040570.92,2020-04-27T19:22:50.920000-07:00,TripDiaryStateMachineService : isLocationUsable() false
139,1588040571.0279999,2020-04-27T19:22:51.028000-07:00,"NotificationHelper : Generating notify with id 87225377, message Error 6 in location settings and pending intent PendingIntent{ae39a78: android.os.BinderProxy@cc98551}"
```

**Comment by asiripanich** [comment] 2020-04-29 02:49
I can't seem to find a guide how to enable fused location or what exactly that is.. But I suspect that the phone's battery optimisation setting overwrites the location permission of the app.

**Comment by shankari** [comment] 2020-04-29 02:56
Fused location combines GPS, WiFi, cellular and bluetooth for best accuracy.
See "Google Location Services" in
https://support.google.com/accounts/answer/3467281?hl=en

**Comment by asiripanich** [comment] 2020-04-29 02:59
I'm not an Android user. Is this not on by default?

**Comment by shankari** [comment] 2020-04-29 03:00
Not sure what the default is - my test phones all have the correct setting.
@atton16 you have an android phone right, do you remember this?

**Comment by asiripanich** [comment] 2020-04-29 03:06
@shankari our test android phone is with me. I never have any issue with that. 

It is probably the battery optimization software on the reported user's phone (a Samsung galaxy S9). 

Just for your information, the default mode for the Samsang phone is called "Medium power saving mode" and apparently it limits background services on the phone. If this is the default by all Samsung phones then we will have a significant amount of participants with android devices complaint about this..

**Comment by shankari** [comment] 2020-04-29 03:51
@asiripanich I am aware of the issues with background operation on some phones - Redmi and Huawei for example. As you point out, background services are limited and you have to tell users to override it.

However, in this case, there are no issues with background operation. If you look at the sync, it is automatically launched every 2-3 hours.

And we are explicitly getting an error from Google Play Services. If this was a Samsung restriction, Google wouldn't know what was wrong.

Try changing the settings on your test android phone away from fused location and see if you get the error.

**Comment by shankari** [comment] 2020-04-29 05:17
make sure to refresh the settings and force a transition of `initialize` so that it will initialize instead of waiting for the next time you take a trip.

**Comment by asiripanich** [comment] 2020-04-30 11:04
@shankari I have an update. After the user switched away from "Medium power saving mode", emTripLog's detection and sync are working now.

**Comment by shankari** [comment] 2020-04-30 15:51
Hm. That is very unexpected!

Three quick comments:
- are you sure that the user didn't also change location settings?
- is it possible to disable the background restrictions for this app alone instead of for the OS as a whole?
- as part of the instructions screen at onboarding, just like we detect the OS and version, we can also detect the phone model. Once we figure out the least disruptive fix, we can put in tailored instructions into that screen.

**Comment by shankari** [comment] 2020-04-30 15:54
it looks like you can turn it on/off for certain apps.
https://us.community.samsung.com/t5/Galaxy-S10/No-longer-receiving-GMail-notifications/td-p/507103

> I was having the same issue with my S10 with gmail not sending notifications. I found if you go to settings > search for "special access" > optimize battery usage > turn of the gmail app, I started getting notifications again even while on medium power saving mode. I'm not sure if you've tried this yet but it seems to be working again normally for me? Hope this helps.

**Comment by shankari** [comment] 2020-05-01 03:44
@asiripanich 

wrt

> as part of the instructions screen at onboarding, just like we detect the OS and version, we can also detect the phone model. Once we figure out the least disruptive fix, we can put in tailored instructions into that screen.

Here's an untested patch that shows the broad idea.
[samsung.untested.patch.gz](https://github.com/e-mission/e-mission-docs/files/4562412/samsung.untested.patch.gz)

However, I am still a bit surprised that background restrictions would affect tracking but not sync. Did you get confirmation that this was the **only** change that the user did?

**Comment by asiripanich** [comment] 2020-05-01 04:00
@shankari Yes that is what i was told. The user also mentioned that as soon as he switched the mode he could see a GPS icon in red (active?) at the top of the screen.

**Comment by asiripanich** [comment] 2020-05-01 04:01
> @asiripanich
> 
> wrt
> 
> > as part of the instructions screen at onboarding, just like we detect the OS and version, we can also detect the phone model. Once we figure out the least disruptive fix, we can put in tailored instructions into that screen.
> 
> Here's an untested patch that shows the broad idea.
> [samsung.untested.patch.gz](https://github.com/e-mission/e-mission-docs/files/4562412/samsung.untested.patch.gz)
> 
> However, I am still a bit surprised that background restrictions would affect tracking but not sync. Did you get confirmation that this was the **only** change that the user did?

Is this just another chuck of text after the consent page?

**Comment by shankari** [comment] 2020-05-01 04:04
It is another chunk of text on the existing sensor_explanation page. But it will displayed only on samsung phones.

**Comment by asiripanich** [comment] 2020-05-01 04:17
> It is another chunk of text on the existing sensor_explanation page. But it will displayed only on samsung phones.

It is becoming more and more complicated for an average person to join a mobile-based mobility survey isn't it? :)

**Comment by shankari** [comment] 2020-05-01 04:18
yeah the problem with the custom versions of android is that they don't allow you to modify their restrictions programatically by prompting the user. So have to add a bunch of text instructions.

**Comment by asiripanich** [comment] 2020-05-01 04:44
Have you gathered enough complaints to write an interesting paper about the current state of mobile-based travel survey? :)

**Comment by asiripanich** [comment] 2020-05-06 23:44
> it looks like you can turn it on/off for certain apps.
> https://us.community.samsung.com/t5/Galaxy-S10/No-longer-receiving-GMail-notifications/td-p/507103
> 
> > I was having the same issue with my S10 with gmail not sending notifications. I found if you go to settings > search for "special access" > optimize battery usage > turn of the gmail app, I started getting notifications again even while on medium power saving mode. I'm not sure if you've tried this yet but it seems to be working again normally for me? Hope this helps.

I checked with the user and the user said that emTripLog wasn't on the list to begin with.

**Comment by shankari** [comment] 2020-05-06 23:55
Hm, how about the workarounds here?
https://www.geekdashboard.com/stop-android-killing-apps-background

I am really trying hard to avoid an OS level setting change, but may not have a choice ☹️

**Comment by shankari** [comment] 2020-05-06 23:58
this actually looks super confusing and has many variations depending on which phone version you have. 
https://dontkillmyapp.com/samsung

I'm thinking of adding a link to https://dontkillmyapp.com but wonder if that would be too confusing.

**Comment by shankari** [comment] 2020-05-07 00:02
ah wait, they have an API, very cool!
https://github.com/urbandroid-team/dont-kill-my-app#api

Let me see if I can just use the API directly. Don't see a way in the API to distinguish between models. But can the user try the Sleeping apps option to see if that fixes the problem?

**Comment by asiripanich** [comment] 2020-05-07 00:06
btw, since we are dealing with this permission issue. Would it be possible to add a shortcut that open up the emTripLog setting on the phone? you know.. the one that let you configure which permissions you want to allow the app to have access to. This way iOS users can change properly configure their location permission of emTripLog to be 'Always allow'.

**Comment by asiripanich** [comment] 2020-05-07 00:09
> ah wait, they have an API, very cool!
> https://github.com/urbandroid-team/dont-kill-my-app#api
> 
> Let me see if I can just use the API directly. Don't see a way in the API to distinguish between models. But can the user try the Sleeping apps option to see if that fixes the problem?

And Huawei and Samsung are at the top! no wonder we have many problems with their phones..

**Comment by shankari** [comment] 2020-05-07 00:11
I assume that would require a native call to a plugin that is not installed. But if you can find the actual call I need to make, I will see if it is possible.

**Comment by shankari** [comment] 2020-05-10 05:35
I would really like to use https://dontkillmyapp.com/ for this since it covers multiple other manufacturers and models. But it doesn't have an entry for the "Medium power saving mode" workaround reported here. Can you submit an entry to them with the full details, including the exact Samsung model and the OS version?
https://github.com/urbandroid-team/dont-kill-my-app#add-a-new-vendor--edit-existing-vendor

**Comment by shankari** [comment] 2020-05-10 14:08
@asiripanich is there an ETA for this? I would like to finish this over the weekend since my time during the week is now very limited.

**Comment by asiripanich** [comment] 2020-05-10 14:14
Hi Shankari

I have to wait until tmr to get the android version of the user’s phone. Or did emTripLog record that at some point?

**Comment by asiripanich** [comment] 2020-05-10 14:57
Just got another feedback from the user 

“I had so many trips today. Only one is recorded. Furthermore my trips from yesterday that were recorded are now gone.
Then I closed and reopened it and then it seems to be working for activities of today but activities of yesterday are gone.
The issue of last week is still there with no improment“

**Comment by shankari** [comment] 2020-05-10 15:03
The issue from last week was a server issue.

I suspect this is similar - "my trips from yesterday that were recorded are now gone" indicates that the trips were uploaded to the server but are not visible any more because there are connection issues to the server. 

Check to see if the user trips from yesterday are on the server: if so, this is a server communication issue.

**Comment by shankari** [comment] 2020-05-10 17:02
Closing this since the original issue was a background restriction on Samsung, and the way to address that in the app is tracked in #535

**Closed by shankari** 2020-05-10 17:02 UTC
