### ISSUE TITLE
error 500 in the Dashboard filter date selection

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#339] opened 2019-03-12 08:49 UTC
In the Dashboard, when I "change data", on the Filter tab (I selected a range with 2 successive days in January because this is the only date range for the moment that shows some indicators when using the Range tab)

I get a 'while pushing/getting from server HTTP/1.1 500 Internal Server Error' message.
On the server output log this is : 
```
START 2019-03-12 09:42:54.055411 POST /result/metrics/timestamp
START 2019-03-12 09:42:54.069391 POST /result/metrics/local_date
END 2019-03-12 09:42:54.515391 POST /result/metrics/timestamp  0.4595179557800293 
END 2019-03-12 09:42:54.589753 POST /result/metrics/local_date 91bc554a-4228-4afd-b2ca-be8eb7e33760 0.5202398300170898 
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 2004, in wrapper
    json_response = dumps(rv)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/bson/json_util.py", line 403, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'int64' is not JSON serializable
```

**Comment by PatGendre** [comment] 2019-03-12 08:50
the bug might be related to https://github.com/e-mission/e-mission-docs/issues/294#issuecomment-348872771

**Comment by shankari** [comment] 2019-03-25 15:24
So I went back and looked at #294 in detail, and it looks like the bson implementation in python3 does not work with integers. I tried to file an issue against the bson library, but they were not supportive of fixing it in the library. So as a workaround, I just converted all possible integers into `float()` before saving them. I guess I need to do this for the metrics outputs as well, which are not stored in the database, but returned from the webapp.

**Comment by PatGendre** [comment] 2019-03-25 15:37
Ok, thanks, I hope it is not a too tricky problem. we just checked that the error on 500 is still there on the filter tab date selector, for 2 consecutive days.

Also (a separate issue presumably), we have noticed that it is not possible to select the saturdays in the date pickup widget.

**Comment by shankari** [comment] 2019-03-25 15:40
@PatGendre you anticipated my next question! Glad to see that the problem is reproducible; it makes it much easier to fix. Maybe I can send you a patch so that you can verify that it fixes the problem before I merge the fix into master...

**Comment by shankari** [comment] 2019-03-26 00:49
ok so looking through the call stack for this function, the `/result/metrics/<time_type>` calls use 
`emission/net/api/metrics.py`, which in turn calls methods in `emission.analysis.result.metrics.time_grouping`.

Look at one of these methods (`group_by_timestamp`), the first part is all about selecting the sections that match, which doesn't touch the result. The second part (`grouped_to_summary`) creates the result to return `ecwms.ModeStatTimeSummary` and fills it in.

`grouped_to_summary` itself just fills in plain integers, but then it calls the `summary_fn` to fill in the actual values.

and of the summary functions defined in `emission/analysis/result/metrics/simple_metrics.py`, except for count, all return some dataframe/numpy related value. I guess in that particular case, the result was an `int`, not a `float`. So if we put `float()` around all of those return values, we should be fine.

**Comment by shankari** [comment] 2019-03-26 00:51
@PatGendre the proposed patch is pretty simple (see below). I've also attached it as a file. Please let me know if this fixes the issue.

```
diff --git a/emission/analysis/result/metrics/simple_metrics.py b/emission/analysis/result/metrics/simple_metrics.py
index 6e8a33b3..53b8304d 100644
--- a/emission/analysis/result/metrics/simple_metrics.py
+++ b/emission/analysis/result/metrics/simple_metrics.py
@@ -27,13 +27,13 @@ def get_count(mode_section_grouped_df):
 def get_distance(mode_section_grouped_df):
     ret_dict = {}
     for (mode, mode_section_df) in mode_section_grouped_df:
-        ret_dict[mode] = mode_section_df.distance.sum()
+        ret_dict[mode] = float(mode_section_df.distance.sum())
     return ret_dict

 def get_duration(mode_section_grouped_df):
     ret_dict = {}
     for (mode, mode_section_df) in mode_section_grouped_df:
-        ret_dict[mode] = mode_section_df.duration.sum()
+        ret_dict[mode] = float(mode_section_df.duration.sum())
     return ret_dict

 def get_median_speed(mode_section_grouped_df):
@@ -45,5 +45,5 @@ def get_median_speed(mode_section_grouped_df):
         if np.isnan(mode_median):
             logging.debug("still found nan for mode %s, skipping")
         else:
-            ret_dict[mode] = mode_median
+            ret_dict[mode] = float(mode_median)
     return ret_dict
```

[fix_metrics_500_error.patch.gz](https://github.com/e-mission/e-mission-docs/files/3006030/fix_metrics_500_error.patch.gz)

**Comment by PatGendre** [comment] 2019-04-08 12:57
the patch is correcting the bug : I don't have an error 500 when I pick 2 consecutive dates in the date filter in the dashboard. Thanks! I don't close the issue because this needs to be merged in phone-app.

**Comment by shankari** [comment] 2019-04-19 15:36
Fixed in https://github.com/e-mission/e-mission-server/commit/88fef81582d7706d22525d0beefcba4149441f0a
Note that the fix is to the server, not the phone.

**Closed by shankari** 2019-04-19 15:36 UTC
