### ISSUE TITLE
Dashboard Errors on Android

### ISSUE THREAD

**Issue by Abby-Wheelis** [e-mission/e-mission-docs#947] opened 2023-08-13 02:31 UTC
Pulling from [issue#932](https://github.com/e-mission/e-mission-docs/issues/932#issuecomment-1676132792) to track an issue with dashboard errors on Android. Errors on the dashboard are popping up on certain Android OS versions. Each error relates to something being undefined, seeming like the CO2 mapping is failing. Since migration of the dashboard is one of our next priorities, we should include investigating and fixing this error in our migration.

**Comment by shankari** [comment] 2023-08-13 03:57
It is 100% reproducible on my android 6 (Nexus).
We should try to create an android 6 avd (API 23), but if that is hard, we can get you a Nexus instead 😄 
If this is too hard to fix, we should consider setting the minSDK to API 24 (Android 7)

**Comment by Abby-Wheelis** [comment] 2023-08-14 17:30
For the "drove_alone" error shown in the comment linked above, I just went through the code base to try and mark where the error might be coming from.

Based on the tracebacks, there is an error being thrown when [`getMet`](https://github.com/e-mission/e-mission-phone/blob/e91c8d05a5e84cd1a538a5e76dbb5515fba748cc/www/js/metrics-factory.js#L189) function is called. Based on the error "cannot read property drove_alone of undefined" it seems like  current METs could be the thing that is undefined here, since a few lines above `mode` is used in an if statement, and that clears. `let currentMETs = cc.getMETs();
if (!currentMETs[mode]) {`

That function (where the error is thrown) is called by [`fillCalorieAggVals`](https://github.com/e-mission/e-mission-phone/blob/e91c8d05a5e84cd1a538a5e76dbb5515fba748cc/www/js/metrics.js#L776) which is called by [`fillAggregateValues`](https://github.com/e-mission/e-mission-phone/blob/e91c8d05a5e84cd1a538a5e76dbb5515fba748cc/www/js/metrics.js#L648) at which point the stack gets a little difficult to trace back, at least sifting through the code base, but I'd assume the originating call is from the code that displays the dashboard.

**Comment by Abby-Wheelis** [comment] 2023-08-14 17:42
The "walk" error seems to be thrown in the same `getMet` function, just called from a different context. This makes me think that it's even more likely to be that `getMETs()` is returning undefined.

code for getMETs() -> 
` cc.getMETs = function() {
    if (this.useCustom == true) {
        return CustomDatasetHelper.getCustomMETs();
    } else {
        return METDatasetHelper.getStandardMETs();
    }}`

This could be an issue with either function (and in either Helper), and I think I should be able to learn more once I find a way to reproduce, but this would be the first place I plan to put breakpoints once I do.

**Comment by shankari** [comment] 2023-08-14 17:45
- I think you can tackle this when you tackle the dashboard rewrite (when you will need to understand/clean up this code anyway)
- have you been able to set up an android 6 avd so you can try to reproduce?

**Comment by Abby-Wheelis** [comment] 2023-08-14 17:47
Not quite yet, but my Java install just got approved so maybe I will be able to reproduce later today!

**Comment by Abby-Wheelis** [comment] 2023-08-14 22:58
I can now run the emulator with Android 6, but unfortunately I'm just getting a blank white screen. I've tried on the branch I was actively working on as well as `framework_migration_prep` and got the same issue both times. So I have not reproduced yet, but now I can run in Android when it comes time to work on the dashboard.

**Comment by shankari** [comment] 2023-08-15 03:01
@Abby-Wheelis I am 99% sure this is because your WebView has not been updated. Can you try  to get an emulator with Google Play Services installed and update the emulator that way?

e.g. change `setup/android_sdk_packages`, install the API 23 version of `system-images;android-24;google_apis_playstore;x86` and create an avd using it

If that doesn't work, I will just mail you a physical android 6 phone

**Comment by Abby-Wheelis** [comment] 2023-08-15 15:07
It appears that there is no `google_apis_playstore` for API 23 available for install. These are the `system-images` that I see for `android-23` when I run `sdkmanager --list`:
![Screenshot 2023-08-15 at 9 03 31 AM](https://github.com/e-mission/e-mission-docs/assets/54848919/c5a53609-16a5-4ed3-ac73-a581a8696de6)
(I have a couple of `google_apis` options but none with `google_apis_playstore`)

Do you think any of the options in the list have the WebView needed?

**Comment by JGreenlee** [comment] 2023-08-15 17:33
> Do you think any of the options in the list have the WebView needed?

It doesn't matter what version of WebView the emulator comes with; you just need some emulator that has the Play Store on it.

On Android, you can update the WebView through the Play Store – different than iOS where the Safari version is baked into the OS and synced with iOS version.

**Comment by shankari** [comment] 2023-08-15 21:20
@Abby-Wheelis you are right that there do not appear to be system images for android-23 with the play store

```
  system-images;android-23;android-tv;armeabi-v7a                                          | 12           | Android TV ARM EABI v7a System Image
  system-images;android-23;android-tv;x86                                                  | 21           | Android TV Intel x86 Atom System Image
  system-images;android-23;default;arm64-v8a                                               | 7            | ARM 64 v8a System Image
  system-images;android-23;default;armeabi-v7a                                             | 6            | ARM EABI v7a System Image
  system-images;android-23;default;x86                                                     | 10           | Intel x86 Atom System Image
  system-images;android-23;default;x86_64                                                  | 10           | Intel x86_64 Atom System Image
  system-images;android-23;google_apis;arm64-v8a                                           | 33           | Google APIs ARM 64 v8a System Image
  system-images;android-23;google_apis;armeabi-v7a                                         | 33           | Google APIs ARM EABI v7a System Image
  system-images;android-23;google_apis;x86                                                 | 33           | Google APIs Intel x86 Atom System Image
  system-images;android-23;google_apis;x86_64                                              | 33           | Google APIs Intel x86_64 Atom System Image
```

**Comment by shankari** [comment] 2023-08-16 22:45
we are going to upgrade to a minSDK of 24+ (Android 7) for the next API upgrade, ETA in a couple of weeks
https://github.com/e-mission/e-mission-docs/issues/934#issuecomment-1679823385

**Comment by Abby-Wheelis** [comment] 2023-08-16 23:02
I'll keep an eye on errors in these spots when we start rewriting the dashboard, but I'm willing to assume it's an issue with Android 6 itself (Google stopped support in 2019), especially if that's the only place we're seeing that particular error.

**Comment by shankari** [comment] 2023-08-18 05:05
After we are done with the dashboard rewrite, if you are not able to reproduce this while testing it, we should close this issue

**Comment by Abby-Wheelis** [comment] 2023-08-22 22:36
<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/e1da7679-97be-4e1e-8994-39735472d3ef" height="600"  /> <img src="https://github.com/e-mission/e-mission-docs/assets/54848919/a77f668b-d502-4bc6-b1b0-21574f5f7c01" height="600"  />

After staging release 1.4.4, I'm seeing dashboard errors on both of my Android test devices again 😞 Both devices have recent trips, most of which are labeled "gas car drove alone"

**Comment by shankari** [comment] 2023-08-22 22:55
so we are not able to find the `getCorrectedMetFromUserData`. I wonder if this is related to the changes to read the user labels from the config. If you use these tokens in the devapp, do you get the same error? Can you put a breakpoint and see if the label options are read correctly?

My Pixel is on a timeuse config, so I can't test this.

**Comment by shankari** [comment] 2023-08-23 00:24
While running the iOS version of NREL OpenPATH on an emulator, I get a 100% reproducible error in the dashboard.
But I think it may be due to lack of data....

```
[Log] Error loading aggregate data, averages not availableundefined is not an object (evaluating 'r[e]') (cordova.js, line 1413)
@ionic://localhost/dist/bundle.js:2:6844024
@ionic://localhost/dist/bundle.js:2:6771352
@ionic://localhost/dist/bundle.js:2:6768881
@ionic://localhost/dist/bundle.js:2:6765978
promiseReactionJob@[native code]
[Log] ERROR:Error loading aggregate data, averages not availableundefined is not an object (evaluating 'r[e]') (cordova.js, line 1413)
@ionic://localhost/dist/bundle.js:2:6844024
@ionic://localhost/dist/bundle.js:2:6771352
@ionic://localhost/dist/bundle.js:2:6768881
@ionic://localhost/dist/bundle.js:2:6765978
promiseReactionJob@[native code]
[Error] undefined is not an object (evaluating 'e.toFixed')
ionic://localhost/dist/bundle.js:2 – "<rangedisplay range=\"carbonData.aggrCarbon\">"
	(anonymous function) (bundle.js:2:709682)
	We (bundle.js:2:705879)
	oe (bundle.js:2:701274)
	(anonymous function) (bundle.js:2:703625)
	(anonymous function) (bundle.js:2:743269)
	(anonymous function) (bundle.js:2:743406)
	$digest (bundle.js:2:748634)
	(anonymous function) (bundle.js:2:750265)
	f (bundle.js:2:683713)
	(anonymous function) (bundle.js:2:685070)
[Error] undefined is not an object (evaluating 'e.toFixed')
ionic://localhost/dist/bundle.js:2 – "<rangedisplay range=\"caloriesData.aggrCalories\">"
	(anonymous function) (bundle.js:2:709682)
	We (bundle.js:2:705879)
	oe (bundle.js:2:701274)
	(anonymous function) (bundle.js:2:703625)
	(anonymous function) (bundle.js:2:743269)
	(anonymous function) (bundle.js:2:743406)
	$digest (bundle.js:2:748634)
	(anonymous function) (bundle.js:2:750265)
	f (bundle.js:2:683713)
	(anonymous function) (bundle.js:2:685070)
```

<img width="386" alt="Screenshot 2023-08-22 at 5 24 04 PM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/ff604295-b6cc-403f-b376-eabac8a4417d">

**Comment by shankari** [comment] 2023-08-23 00:32
If this is intermittent, I suspect a timing error. In which case, we should be able to workaround it/reduce it to low enough levels by just adding a timeout while loading the trip options. That might be enough for this release, and we can get the rewritten dashboard into the next release.

**Comment by Abby-Wheelis** [comment] 2023-08-23 15:38
With breakpoints: found that `getMETs` is returning undefined, we are using custom METs so need to check `CustomDatasetHelper.getCustomMETs`

That function (`getCustomMETs`) is just a return for the `customMETs` stored in the custom dataset helper
They get initialized by an init function, which, judging by a breakpoint in it never tripping, is not getting run!

I'm planning to look into when this should be initialized (any why it is not) as my next step

**Comment by Abby-Wheelis** [comment] 2023-08-23 16:22
I found something! So in ` cdh.populateCustomMETs` and `cdh.populateCustomFootprints`, which are functions that initialize the custom options on initialization, the custom setting rely on the "MODE" options from the `inputParams` read in from the config file. In both places, the options were being accessed as `cdh.inputParams["MODE"].option` where the result of `cdh.inputParams["MODE"]` seems to be an array of mode objects (already the options?) but does not have an `options` attribute. I removed `.options` from both functions and it works now!

Next step to test on more of my opCodes where I'm seeing the error on staging

**Comment by Abby-Wheelis** [comment] 2023-08-23 16:33
Happy to report that this fix works on all three of my staging opCodes (2 Android, 1 iPhone, 2 study, 1 program) all three of which I am getting errors 100% of the time on the dashboard on the physical device, but not on the emulator with this fix. 

Next I'll move to drafting a PR with this fix

**Comment by shankari** [comment] 2023-08-23 17:16
I guess we changed the format in which those options were stored as part of the "configurable options" feature.
@Abby-Wheelis great job!

**Closed** 2023-08-23 17:18 UTC

**Comment by JGreenlee** [comment] 2023-08-23 17:24
Thanks for fixing! Yes, I did remove the `options` field because it was the only property at that level and it simplified the data structure to flatten it by one level.

I thought I had handled everywhere that `options` was used, but I must have missed this one. Good catch!
