### ISSUE TITLE
DuplicateKey Error

### ISSUE THREAD

**Issue by myaman17** [e-mission/e-mission-docs#356] opened 2019-04-03 16:08 UTC
I am getting the following error:
![image](https://user-images.githubusercontent.com/31378904/55494682-16877980-55f0-11e9-9283-ab544a0ef9f1.png)

line 314, in _check_write_command_response
raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: Stage_database.Stage_timeseries index: id dup key: { : ObjectId('579885da88f66352f9233649') }
(emission)

**Comment by shankari** [comment] 2019-04-10 16:52
@myaman17 I tried to reproduce this by re-downloading the data for your client (`megumi-brt`) and loading it locally. I was not able to reproduce the error

```
INFO:root:For 234 users, loaded 192278 raw entries, 0 processed entries and 0 pipeline states
INFO:root:all entries in the timeline contain only raw data, need to run the intake pipeline
```

So I wonder if you tried to load the data earlier and there is some leftover data in the database that is causing the `DuplicateError`.

Can you purge the database (`bin/purge_database.py`) and reload?

**Comment by shankari** [comment] 2019-04-10 16:53
Also, when I was loading the data today, I found multiple users who had more than 10000 entries so their data was loaded in batches. When you are loading, see if you find them too. Otherwise, it may be that some users kept the data installed for longer than you had asked and you may have months of data from them...

**Comment by shankari** [comment] 2019-04-10 16:55
A concrete example is user with uuid `0313d08e-dceb-4ea4-9214-322cf44d55d6` who has `198874` entries.

**Comment by myaman17** [comment] 2019-04-10 23:40
I understand. Thank you for your detailed explanations!

**Comment by shankari** [comment] 2019-04-10 23:56
@myaman17 did you check the number of entries that you have while loading the two uuids in 
https://github.com/e-mission/e-mission-docs/issues/356#issuecomment-481773792

Just want to check whether I have more data that I should send to you...

**Comment by myaman17** [comment] 2019-04-11 00:27
No. They are not in my data. I will need those data. Thank you for double checking!!

**Comment by PatGendre** [comment] 2019-04-11 09:26
Hi, I had the same error when tring to load data extracted from our server into my local db.

For one user, I have ca 15000 entries so I tried with the --batch-size 20000 option (and purged the db before running `load_multi_timeline_for_range.py`) but I have this error `pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: Stage_database.Stage_timeseries index: _id_ dup key: { : ObjectId('5c9df5ab3070fe2fdf2db433') }`

**Comment by shankari** [comment] 2019-04-11 14:25
hm, I ran the load script twice yesterday on @myaman17's data and did not run into this. I wonder if this is a Windows-specific issue. @PatGendre is your laptop Windows?

**Comment by PatGendre** [comment] 2019-04-11 14:27
No, I am on ubuntu (I have windows as well, it is a double boot).
However I tried the `bin/debug/load_timeline_for_day_and_user.py` instead on single timeline files and it works well:-)

**Comment by shankari** [comment] 2019-04-11 14:35
@PatGendre if on ubuntu can you see whether there actually are duplicate ids in the raw data? so for the user whose data generated the error, can you grep and see if there are really two entries with object id `5c9df5ab3070fe2fdf2db433`?

It should be fine to use `bin/debug/load_timeline_for_day_and_user.py` on the single timeline files as long as you haven't run the pipeline on the raw data. Otherwise, I think it will put the analysis results (e.g. `analysis/cleaned_trip`) also into the timeseries collection instead of the analysis_timeseries collection.

**Comment by PatGendre** [comment] 2019-04-11 14:54
yes there are 2 occurrences of the same objectid.
it is a motion_activity data, and the timestamp is the same for the 2 occurrences.

**Comment by PatGendre** [comment] 2019-04-11 15:30
yes there are 2 occurrences of the same objectid.
it is a motion_activity data, and the timestamp is the same for the 2 occurrences.

**Comment by PatGendre** [comment] 2019-04-11 15:34
concerning the `load_timeline_for_day_and_user.py` script, actually my timeline files don't contain `analysis` data so anyway only `stats` and `background` data are imported in the `timeseries` collection.
And even if the script would insert the analysis data in the `timeseries` collection, if I clean the analysis_timeseries collection and re-run the pipeline it would work, I guess?

**Comment by shankari** [comment] 2019-04-11 16:35
> yes there are 2 occurrences of the same objectid.
> it is a motion_activity data, and the timestamp is the same for the 2 occurrences.

Hm so there is an issue with the extraction, not the load. That would explain why I am not able to reproduce @myaman17's issue -  the previous data that I extracted is encrypted with her key and I can't access it; so I re-extracted her data.

I would like to debug this further, but I don't have time right now. A workaround would be to add a try/except block in `emission/storage/timeseries/cache_series.py`, something like 

```
    for entry in entry_it:
        try:
            assert entry["user_id"] is not None, "user_id for entry %s is None, cannot insert" % entry
            if "write_fmt_time" in entry["metadata"]:
                # write_fmt_time is filled in only during the formatting process
                # so if write_fmt_time exists, it must be in the timeseries already
                ts.insert(entry)
                tsdb_count = tsdb_count + 1
            else:
                ucdb.save(entry)
                ucdb_count = ucdb_count + 1
        except:
               logging.warn("Found exception while storing entry %s with key %s, skipping" % entry["_id"], entry["metadata"]["key"])
```
I haven't tested that since I can't reproduce it, but you get the general idea.

**Comment by PatGendre** [comment] 2019-04-11 16:41
Yes, Ok, thanks! maybe @myaman17 has the kind of duplicate than I do, which is possible to suppress by hand in the file for the moment, as there seems to be only one objectid duplicate in the file (I didn't test to reload, though).

**Comment by shankari** [comment] 2019-04-11 16:42
> It should be fine to use bin/debug/load_timeline_for_day_and_user.py on the single timeline files as long as you haven't run the pipeline on the raw data. Otherwise, I think it will put the analysis results (e.g. analysis/cleaned_trip) also into the timeseries collection instead of the analysis_timeseries collection.

I take this back. This used to be true, but in some recent refactoring, I have done the right thing and unified the code paths. Both `load_multi_timeline_for_range.py` and `load_timeline_for_day_and_user.py` call `estcs.insert_entries`, which, downstream, calls `builtin_timeseries.insert` which puts the entry into the correct timeseries.

Yay me!

**Comment by shankari** [comment] 2019-04-11 16:42
> It should be fine to use bin/debug/load_timeline_for_day_and_user.py on the single timeline files as long as you haven't run the pipeline on the raw data. Otherwise, I think it will put the analysis results (e.g. analysis/cleaned_trip) also into the timeseries collection instead of the analysis_timeseries collection.

I take this back. This used to be true, but in some recent refactoring, I have done the right thing and unified the code paths. Both `load_multi_timeline_for_range.py` and `load_timeline_for_day_and_user.py` call `estcs.insert_entries`, which, downstream, calls `builtin_timeseries.insert` which puts the entry into the correct timeseries.

Yay me!

**Comment by shankari** [comment] 2019-04-11 16:44
> It should be fine to use bin/debug/load_timeline_for_day_and_user.py on the single timeline files as long as you haven't run the pipeline on the raw data. Otherwise, I think it will put the analysis results (e.g. analysis/cleaned_trip) also into the timeseries collection instead of the analysis_timeseries collection.

I take this back. This used to be true, but in some recent refactoring, I have done the right thing and unified the code paths. Both `load_multi_timeline_for_range.py` and `load_timeline_for_day_and_user.py` call `estcs.insert_entries`, which, downstream, calls `builtin_timeseries.insert` which puts the entry into the correct timeseries.

So they are interchangeable in terms of loading the timeline data - `load_multi_timeline_for_range.py` had additional functionality for loading the timeline state and the email <-> uuid map.

Yay me!

**Comment by shankari** [comment] 2019-04-11 16:44
> It should be fine to use bin/debug/load_timeline_for_day_and_user.py on the single timeline files as long as you haven't run the pipeline on the raw data. Otherwise, I think it will put the analysis results (e.g. analysis/cleaned_trip) also into the timeseries collection instead of the analysis_timeseries collection.

I take this back. This used to be true, but in some recent refactoring, I have done the right thing and unified the code paths. Both `load_multi_timeline_for_range.py` and `load_timeline_for_day_and_user.py` call `estcs.insert_entries`, which, downstream, calls `builtin_timeseries.insert` which puts the entry into the correct timeseries.

So they are interchangeable in terms of loading the timeline data - `load_multi_timeline_for_range.py` had additional functionality for loading the timeline state and the email <-> uuid map.

Yay me!

**Comment by shankari** [comment] 2019-04-11 16:47
@myaman17 I am sending you the newly updated data separately. It is encrypted with the same keys as last time :)

**Comment by shankari** [comment] 2019-08-12 21:33
I was just able to reproduce this while pulling out some evaluation data from cardshark.

```
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: Stage_database.Stage_timeseries index: _id_ dup key: { : ObjectId('5a930133d1eb28ef5693e57f') }
```

Investigating further...

**Comment by shankari** [comment] 2019-08-12 21:42
As I saw before, there are in fact two entries in the extracted data

```
$ zgrep "5a930133d1eb28ef5693e57f" /tmp/invalid_ios_points_c76a0487-7e5a-3b17-a449-47be666b36f6.gz
            "$oid": "5a930133d1eb28ef5693e57f"
            "$oid": "5a930133d1eb28ef5693e57f"
```

and the matching entry is 

```
{'_id': ObjectId('5a930133d1eb28ef5693e57f'),
 'data': {'automotive': False,
  'confidence': 100,
  'confidence_level': 'high',
  'cycling': False,
  'fmt_time': '2018-02-25T00:02:56.800303-08:00',
  'running': False,
  'stationary': False,
  'ts': 1519545776.800303,
  'type': 9,
  'unknown': False,
  'walking': False},
 'metadata': {'key': 'background/motion_activity',
  'platform': 'ios',
  'plugin': None,
  'read_ts': 0,
  'time_zone': 'America/Los_Angeles',
  'type': 'sensor-data',
  'write_fmt_time': '2018-02-25T00:02:56.800303-08:00',
  'write_ts': 1519545776.800303},
 'user_id': UUID('c76a0487-7e5a-3b17-a449-47be666b36f6')}
```

and there is only one corresponding entry in the database

```
In [637]: edb.get_timeseries_db().find({"_id": boi.ObjectId("5a930133d1eb28ef5693e57f")}
     ...: ).count()
Out[637]: 1
```

**Comment by shankari** [comment] 2019-08-12 21:49
I used the following command for the extraction

```
$ ./e-mission-py.bash bin/debug/extract_timeline_for_day_range_and_user.py -e ucb.sdb.android.2 ucb.sdb.android.3 ucb.sdb.iphone.2 ucb.sdb.iphone.3 -- 2018-02-25 2018-02-27 /tmp/invalid_ios_points
```

So looking at the timestamp, this should be one of the first entries `2018-02-25T00:02:56.800303-08:00` read

**Comment by shankari** [comment] 2019-08-12 22:08
This entry shows up at lines 244 and 311352.
Let's check the entries around it to see if there are more duplicates.
The next entry at line 244 is 5a930133d1eb28ef5693e581 and there is a duplicate of that at line 311403 as well
And similarly for the next one at `5a930133d1eb28ef5693e583`

Searching backwards for the last `motion_activity` entry, we find duplicate entries

```
311275     {
311276         "_id": {
311277             "$oid": "5a948c74d1eb28ef56a5b614"
311278         },
311279         "metadata": {
311285             "key": "background/motion_activity",
311286             "type": "sensor-data"
311287         },
...
374869     {
374870         "_id": {
374871             "$oid": "5a948c74d1eb28ef56a5b614"
374872         },
374873         "metadata": {
374879             "key": "background/motion_activity",
374880             "type": "sensor-data"
374881         },
```

And the timestamp for those entries is 

```
In [33]: arrow.get(1519675081.0945125).to("America/Los_Angeles")
Out[33]: <Arrow [2018-02-26T11:58:01.094512-08:00]>
```

So it looks like this is not a timestamp issue and we just duplicated a bunch of entries

**Comment by shankari** [comment] 2019-08-12 23:10
Checking the logs for this run and this user, we see the following queries. This is almost certainly due to the second call to retrieve only the motion activity queries. Let's look at the history to figure out why we did that, but I think it is because we expected that `motion_activity` entries would not have a `ts` entry and would not be returned with other sensor data.

Yup, added in c26ebf6ed6c8c54ce3dbdc715d03ae869e066e53, which would also
explain why the new entries are only `motion_activity`.

```
INFO:root:==================================================
INFO:root:Extracting timeline for user c76a0487-7e5a-3b17-a449-47be666b36f6 day 2018-02-25 -> 2018-02-27 and saving to file /tmp/invalid_ios_points
DEBUG:root:start_day_ts = 1519516800 (2018-02-25T00:00:00+00:00), end_day_ts = 1519689600 (2018-02-27T00:00:00+00:00)
```

From the usercache + timeseries database

```
DEBUG:root:curr_query = {'user_id': UUID('c76a0487-7e5a-3b17-a449-47be666b36f6'), 'data.ts': {'$lte': 1519689600, '$gte': 1519516800}}, sort_key = data.ts
DEBUG:root:orig_ts_db_keys = None, analysis_ts_db_keys = None
DEBUG:root:finished querying values for None, count = 4952
DEBUG:root:finished querying values for None, count = 483
DEBUG:root:orig_ts_db_matches = 4952, analysis_ts_db_matches = 483
DEBUG:root:Found 786 messages in response to query {'user_id': UUID('c76a0487-7e5a-3b17-a449-47be666b36f6'), '$or': [{'metadata.type': 'message'}, {'metadata.type': 'sensor-data'}, {'metadata.type': 'rw-document'}], 'data.ts': {'$lte': 1519689600, '$gte': 1519516800}}
```

Separate query only for motion_activity

```
DEBUG:root:curr_query = {'user_id': UUID('c76a0487-7e5a-3b17-a449-47be666b36f6'), '$or': [{'metadata.key': 'background/motion_activity'}], 'metadata.write_ts': {'$lte': 1519689600, '$gte': 1519516800}}, sort_key = metadata.write_ts
DEBUG:root:orig_ts_db_keys = ['background/motion_activity'], analysis_ts_db_keys = []
DEBUG:root:finished querying values for ['background/motion_activity'], count = 841
DEBUG:root:finished querying values for [], count = 0
DEBUG:root:orig_ts_db_matches = 841, analysis_ts_db_matches = 0
DEBUG:root:Found 765 messages in response to query {'user_id': UUID('c76a0487-7e5a-3b17-a449-47be666b36f6'), '$or': [{'metadata.key': 'background/motion_activity'}], 'metadata.write_ts': {'$lte': 1519689600, '$gte': 1519516800}}
```

Trip-like objects from the analysis timeseries

```
DEBUG:root:curr_query = {'user_id': UUID('c76a0487-7e5a-3b17-a449-47be666b36f6'), 'data.start_ts': {'$lte': 1519689600, '$gte': 1519516800}}, sort_key = data.start_ts
DEBUG:root:orig_ts_db_keys = None, analysis_ts_db_keys = None
DEBUG:root:finished querying values for None, count = 0
DEBUG:root:finished querying values for None, count = 76
DEBUG:root:orig_ts_db_matches = 0, analysis_ts_db_matches = 76
```

Place-like objects from the analysis database

```
DEBUG:root:curr_query = {'user_id': UUID('c76a0487-7e5a-3b17-a449-47be666b36f6'), 'data.enter_ts': {'$lte': 1519689600, '$gte': 1519516800}}, sort_key = data.enter_ts
DEBUG:root:orig_ts_db_keys = None, analysis_ts_db_keys = None
DEBUG:root:finished querying values for None, count = 0
DEBUG:root:finished querying values for None, count = 30
DEBUG:root:orig_ts_db_matches = 0, analysis_ts_db_matches = 30
```
...

```
INFO:root:Found 6221 loc entries, 1606 motion entries, 76 trip-like entries, 30 place-like entries = 7935 total entries
```

**Comment by shankari** [comment] 2019-08-12 23:17
There are a couple of potential fixes.
- we restrict the motion_activity query to the usercache instead of using cache_series as below

```
+    ma_time_query = estt.TimeQuery("metadata.write_ts", start_day_ts, end_day_ts)
+    ma_entry_list = list(estcs.find_entries(user_id, key_list=["background/motion_activity"], time_query=ma_time_query))
```

- we use `metadata.write_ts` for both the loc and ma queries since we know that it will always exist.

**Comment by shankari** [comment] 2019-08-12 23:25
I am going to pick (1) for now since using `metadata.write_ts` can have the unintended consequence of returning analysis entries that were created at that time from the pipeline. If we do choose to go with (2), we should add additional checks on the message type as well to prevent this from happening.

**Comment by shankari** [comment] 2019-08-12 23:26
Also, if we start formatting the motion_activity on the phone to include the `ts`, we would not have this problem since the first query would Just Work.

**Closed** 2019-08-15 00:23 UTC
