### ISSUE TITLE
Custom integration of maint_upgrade_2023: issues with splash screen and notifications

### ISSUE THREAD

**Issue by idillon-sfl** [e-mission/e-mission-docs#878] opened 2023-04-05 16:34 UTC
Hi!
We attempted to add the changes from the branch [maint_change_2023](https://github.com/e-mission/e-mission-phone/tree/maint_upgrade_2023) to [our own branch](https://github.com/FabmobQC/mamobilite). Google Play already requires us to upgrade the SDK.

It works, but we still have two issues:
- The splash screen displays the Cordova's logo instead of ours
- The push notifications are received (they can be seen in the log), but they are not displayed anymore. It seems they will even make the app crash in some occasions (we got two crashes while receiving a notification, but we've not been able to reproduce).

Do you have any clue for solving these issues?

Thank you

By the way, I noticed the SDK versions are not updated on these two lines: https://github.com/e-mission/e-mission-phone/blob/maint_upgrade_2023/config.serve.xml#L59. I mention it only because it does not seem right. Updating these lines did not change anything for us

**Comment by shankari** [comment] 2023-04-06 15:47
First, the `config_serve.xml` (aka https://github.com/e-mission/e-mission-phone/#updating-the-ui-only) is for the devapp https://github.com/e-mission/e-mission-devapp that supports quick UI development using auto-reload. It doesn't use the SDK at all since it works only at the javascript level. I do have to update the devapp to capture the native code changes, but will do that after I push to production.

wrt your two comments:
1. I am not very UI-focused, so I don't pay attention to things like the splash screen. The OpenPATH app shows the openpath logo and then the old e-mission logo on launch and I haven't bothered to fix it yet. (or you can think of it as an homage to the original codebase).
    (i) Having said that, the OpenPATH app does show its splash screen correctly. Did you try https://github.com/e-mission/e-mission-phone/#creating-logos? I am pretty sure that is how I generated the splash screen for the OpenPATH app.
   (ii) While building android, I do see this message (which I have ignored so far). I would suggest also trying this; please submit a PR if it helps/is better in any way.

```
The "<splash>" tags were detected and are no longer supported. Please migrate to the "preference" tag "AndroidWindowSplashScreenAnimatedIcon".
```

2. As you can see once you install using the testing channel, push notifications are working for NREL OpenPATH. I don't see any crashes. If you are able to reproduce and can paste the backtrace, I'll be happy to take a look.

**Comment by idillon-sfl** [comment] 2023-04-07 22:39
Thank you for your answer

I had not yet tried a version of OpenPath with all the upgrades when I posted the other day. I installed the version 1.1.7 and I also see the Cordova logo on the splash screen on that one. I don't see any message about the "<splash>" tags when I build our fork for Android, however.

It is comforting to know the push notifications work on OpenPath.

We'll investigate further next week. I'll share any discovery that could be useful to you. Thank you

**Comment by shankari** [comment] 2023-04-10 18:14
@idillon-sfl I should have clarified that we see the OpenPATH splash screen on iOS
We are primarily testing on the iOS emulator since we are not allowed to use Android Studio on our work computers, and installing android emulators from the CLI is a bit of a hassle.

I am surprised that you don't see the message about the splash tags - maybe you need to scroll to the top of the build?
Note that we have CI enabled for this project, so you can check your build output against the expected build output.

<details>
<summary>My build logs, showing the splash screen message</summary>

```
$ npx cordova build android
(node:87204) [DEP0128] DeprecationWarning: Invalid 'main' field in ...node_modules/objectorarray/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
Copying locales: Languages found -> ThirdPartyContributors.md,es,fr,it,lo
Copying locales: I found ThirdPartyContributors.md, I will now copy the files.
Copying locales: ...locales/ThirdPartyContributors.md/values-ThirdPartyContributors.md not found, I will continue.
Copying locales: .../locales/ThirdPartyContributors.md/i18n/ not found, I will continue.
Copying locales: I found es, I will now copy the files.
Copying locales: Copying .../locales/es/values-es to /Users/kshankar/in-house/openpath-phone/platforms/android/app/src/main/res
Copying locales: .../locales/es/values-escopied...
Copying locales: Copying .../locales/es/i18n/ to /Users/kshankar/in-house/openpath-phone/www/i18n/
Copying locales: .../locales/es/i18n/copied...
Copying locales: I found fr, I will now copy the files.
Copying locales: Copying .../locales/fr/values-fr to /Users/kshankar/in-house/openpath-phone/platforms/android/app/src/main/res
Copying locales: .../locales/fr/values-frcopied...
Copying locales: Copying .../locales/fr/i18n/ to /Users/kshankar/in-house/openpath-phone/www/i18n/
Copying locales: .../locales/fr/i18n/copied...
Copying locales: I found it, I will now copy the files.
Copying locales: .../locales/it/values-it to ../platforms/android/app/src/main/res
Copying locales: .../locales/it/values-itcopied...
Copying locales: .../locales/it/i18n/ to .../www/i18n/
Copying locales: .../locales/it/i18n/copied...
Copying locales: I found lo, I will now copy the files.
Copying locales: .../locales/lo/values-lo not found, I will continue.
Copying locales: Copying .../locales/lo/i18n/ to ../www/i18n/
Copying locales: .../locales/lo/i18n/copied...
Changing Providers: Retrieving application name...
Changing Providers: Your application is ...
Changing Providers: Updating AndroidManifest.xml...
Changing Providers: Updating syncadapter.xml
Changing Providers: Updating authenticator.xml
Changing Providers: Updating ServerSyncPlugin.java
Changing compile to implementation Retrieving application name...
Changing compile to implementation Your application is ...
Changing compile to implementation Updating barcode scanner gradle...
/usr/bin/git
Downloading locales: /.../bin/conf/translate_config.json not found, I will extract translate repo from translation_config.json.sample.
Already up to date.
config file *-Info.plist requested for changes not found at .../platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at .../platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at .../platforms/android/*-Info.plist, ignoring
The "<splash>" tags were detected and are no longer supported. Please migrate to the "preference" tag "AndroidWindowSplashScreenAnimatedIcon".
Changing Providers: /.../platforms/android/app/src/main/res/xml/authenticator.xml updated...
Changing Providers: .../platforms/android/app/src/main/AndroidManifest.xml updated...
Changing compile to implementation .../platforms/android/phonegap-plugin-barcodescanner/openpath-barcodescanner.gradle updated...
Changing Providers: .../platforms/android/app/src/main/res/xml/syncadapter.xml updated...
Changing Providers: .../platforms/android/app/src/main/java/edu/berkeley/eecs/emission/cordova/serversync/ServerSyncPlugin.java updated...
cordova-plugin-androidx-adapter: Processed 186 source files in 2794ms
[cordova-plugin-push::before-compile] skipping before_compile hookscript.
Checking Java JDK and Android SDK versions
ANDROID_HOME=undefined (recommended setting)
ANDROID_SDK_ROOT=undefined (DEPRECATED)
Using Android SDK: undefined
Subproject Path: CordovaLib
Subproject Path: app
Starting a Gradle Daemon (subsequent builds will be faster)
```

</details>

**Comment by idillon-sfl** [comment] 2023-04-12 01:17
Interesting, on our side testing for Android is much more convenient. I've not tried yet for iOS.

The command `ionic cordova resources` has been run.  

<details>
<summary>Here my log</summary>
$ cordova build android
Changing Providers: Retrieving application name...
Changing Providers: Your application is com.fabmoqc.mamobilite
Changing Providers: Updating AndroidManifest.xml...
Changing Providers: Updating syncadapter.xml
Changing Providers: Updating authenticator.xml
Changing Providers: Updating ServerSyncPlugin.java
Changing compile to implementation Retrieving application name...
Changing compile to implementation Your application is com.fabmoqc.mamobilite
Changing compile to implementation Updating barcode scanner gradle...
config file *-Info.plist requested for changes not found at /.../platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /.../platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /.../platforms/android/*-Info.plist, ignoring
Changing Providers: /.../platforms/android/app/src/main/res/xml/syncadapter.xml updated...
Changing Providers: /.../platforms/android/app/src/main/res/xml/authenticator.xml updated...
Changing Providers: /.../platforms/android/app/src/main/java/edu/berkeley/eecs/emission/cordova/serversync/ServerSyncPlugin.java updated...
Changing compile to implementation /.../platforms/android/phonegap-plugin-barcodescanner/mamobilite-barcodescanner.gradle updated...
Changing Providers: /.../platforms/android/app/src/main/AndroidManifest.xml updated...
cordova-plugin-androidx-adapter: Processed 158 source files in 2278ms
[cordova-plugin-push::before-compile] skipping before_compile hookscript.
Checking Java JDK and Android SDK versions
ANDROID_HOME=/.../Android/Sdk (recommended setting)
ANDROID_SDK_ROOT=/.../Android/Sdk (DEPRECATED)
Using Android SDK: /.../Android/Sdk
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
Adding classpath: com.google.gms:google-services:4.3.3
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
52 actionable tasks: 52 up-to-date
Built the following apk(s): 
        /.../platforms/android/app/build/outputs/apk/debug/app-debug.apk
</details>

I don't expect to have the exact same result, since the branches diverged.

Sadly, our CI have not been maintained. I hope to have the occasion to do so.

**Comment by shankari** [comment] 2023-04-12 01:27
So mine has 

```
cordova-plugin-androidx-adapter: Processed 186 source files in 2794ms
```

yours has 

```
cordova-plugin-androidx-adapter: Processed 158 source files in 2278ms
```

I wonder if you have actually updated everything successfully

- Have you tried cleaning out your directories and rebuilding? (https://github.com/e-mission/e-mission-phone/#troubleshooting)
- > The command ionic cordova resources has been run.
- Does the resulting `config.xml` have a `splash` tag?

**Comment by idillon-sfl** [comment] 2023-04-17 23:04
Thank you ! You pointed to the right places to solve this splash screen issue. I had never paid attention to this config.xml file before. I did not know `ionic cordova resources` was writting to it, and `bash setup/setup_android_native.sh` would override it.

1.2.2 also has this problem. The solution is to add "AndroidWindowSplashScreenAnimatedIcon" into the config.xml file. [Here some explanations](https://ionic.zendesk.com/hc/en-us/articles/7891143965975-Migrating-to-Cordova-Android-11).  [Here the specifications for the image](https://developer.android.com/develop/ui/views/launch/splash-screen#splash_screen_dimensions).

For the number of sources, I expect us to have less files than the main branch, since we don't implement all pages and functionalities.

For the push notifications, we decided to use local notifications instead. It is still frustrating not to have the push notifications, but I guess local notifications are more appropriate for our current need. I am still thinking it might be a problem with our icons.

**Comment by shankari** [comment] 2023-04-18 04:58
@idillon-sfl 

> For the number of sources, I expect us to have less files than the main branch, since we don't implement all pages and functionalities.

The number of files reported is the number of native code files and only depends on the number of cordova plugins that you have installed. If you have the same number of plugins installed as I do (and I strongly recommend that you do), the number of files should be identical. If you have removed any plugins, which were they? Could that be the reason that the push notifications don't work? Can you confirm that the push notifications do work on the NREL OpenPATH app?

**Comment by shankari** [comment] 2023-04-23 03:29
@idillon-sfl thanks for the update, 1.2.4 now has the proper splash screen.

Also wrt push, the setup scripts also override the `google-services.json` files - you might want to check that they are correct, and not filled with values like `11111111` before building

Also, were you able to figure out which plugin you are missing? As I said, the number of source files should only be affected by the number of plugins installed, not the UI screens on top of the base app.

**Comment by idillon-sfl** [comment] 2023-04-24 18:36
Time goes fast, already a week since your other message.

I was trying to add on our branch only the functionalities we needed. For example, I think we were not including the bar code scanner. But with more experience, I'd say we're better to keep as close as possible to the main branch. After some updates, we now include 23 plugins and 181 source files on android.

We gave up for now with the push notifications. We might try again later if we need them.

**Comment by shankari** [comment] 2023-04-26 01:23
Closing this for now.
@idillon-sfl please open a new issue if/when you return to push notifications

**Closed by shankari** 2023-04-26 01:23 UTC
